/* Copyright (C) 2016-2018 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2018-12-03
// KLL Emitter:        kiibohd
// KLL Version:        0.5.6.6
// KLL Git Changes:    None
// Compiler arguments:
//    /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/__main__.py
//    --kiibohd-debug
//    --config
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/ISSILed/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/MatrixARMPeriodic/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/STLcd/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/UARTConnect/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Macro/PartialMap/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Macro/PixelMap/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Output/HID-IO/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Output/USB/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Debug/latency/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Debug/led/capabilities.kll
//    --base
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/scancode_map.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/leftHand.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/slave1.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/rightHand.kll
//    --default
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/MDErgo1-Default-0.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/infinity_ergodox/lcdFuncMap.kll
//    --partial
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/MDErgo1-Default-1.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/stdFuncMap.kll
//    --partial
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/MDErgo1-Default-2.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/stdFuncMap.kll
//    --emitter
//      kiibohd
//    --def-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/kll_defs.h
//    --map-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/generatedKeymap.h
//    --hid-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/usb_hid.h
//    --pixel-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/generatedPixelmap.c
//    --json-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-L.gcc.make/kll.json
//
// - Configuration File -
//    ISSILedCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll
//    MatrixARMPeriodicCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll
//    STLcdCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_STLcd@['capabilities']_processed.kll
//    UARTConnectCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_UARTConnect@['capabilities']_processed.kll
//    PartialMapCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Macro_PartialMap@['capabilities']_processed.kll
//    PixelMapCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Macro_PixelMap@['capabilities']_processed.kll
//    HID-IOCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Output_HID-IO@['capabilities']_processed.kll
//    USBCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Output_USB@['capabilities']_processed.kll
//    latency
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Debug_latency@['capabilities']_processed.kll
//    led
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Debug_led@['capabilities']_processed.kll
// - Generic Files -
// - Base Layer -
//    Infinity_Ergodox
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['scancode_map']_processed.kll
//    Infinity Ergodox Left Hand
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['leftHand']_processed.kll
//    MDErgo1Slave1
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['slave1']_processed.kll
//    Infinity Ergodox Right Hand
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['rightHand']_processed.kll
// - Default Layer -
//    MDErgo1
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Keyboards_darwin18.0.0.ICED-L.gcc.make@['MDErgo1-Default-0']_processed.kll
//    lcdFuncMap
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll
// - Partial Layers -
//    Layer 1
//     MDErgo1
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Keyboards_darwin18.0.0.ICED-L.gcc.make@['MDErgo1-Default-1']_processed.kll
//     stdFuncMap
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts@['stdFuncMap']_processed.kll
//    Layer 2
//     MDErgo1
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Keyboards_darwin18.0.0.ICED-L.gcc.make@['MDErgo1-Default-2']_processed.kll
//     stdFuncMap
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts@['stdFuncMap']_processed.kll



// ----- Includes -----

// Compiler Includes
#include <stdint.h>

// KLL Includes
#include <kll_defs.h>

// Project Includes
#include <pixel.h>



// LED Buffer Struct

typedef struct LED_Buffer {
	uint16_t i2c_addr;
	uint16_t reg_addr;
	uint16_t buffer[144];
} LED_Buffer;
volatile LED_Buffer LED_pageBuffer[ ISSI_Chips_define ];

typedef struct KLL_Buffer {
	uint16_t buffer[144];
} KLL_Buffer;
volatile KLL_Buffer KLL_pageBuffer[ ISSI_Chips_define ];



// Buffer list
PixelBuf Pixel_Buffers[] = {
	PixelBufElem( 144, 16, 0, KLL_pageBuffer[0].buffer ),
};
PixelBuf LED_Buffers[] = {
	PixelBufElem( 144, 16, 0, LED_pageBuffer[0].buffer ),
};


// Fade Configuration
const uint16_t Pixel_LED_DefaultFadeGroup0[] = {
	1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38
};
const uint16_t Pixel_LED_DefaultFadeGroup1[] = {
};
const uint16_t Pixel_LED_DefaultFadeGroup2[] = {
};
const PixelLEDGroupEntry Pixel_LED_DefaultFadeGroups[] = {
	{ 38, Pixel_LED_DefaultFadeGroup0 },
	{ 0, Pixel_LED_DefaultFadeGroup1 },
	{ 0, Pixel_LED_DefaultFadeGroup2 },
};
const PixelPeriodConfig Pixel_LED_FadePeriods[16] = {
	{ .start = 0, .end = 0 }, // 0
	{ .start = 0, .end = 4 }, // 1
	{ .start = 0, .end = 5 }, // 2
	{ .start = 0, .end = 6 }, // 3
	{ .start = 0, .end = 7 }, // 4
	{ .start = 0, .end = 8 }, // 5
	{ .start = 0, .end = 9 }, // 6
	{ .start = 0, .end = 10 }, // 7
	{ .start = 0, .end = 11 }, // 8
	{ .start = 0, .end = 12 }, // 9
	{ .start = 5, .end = 6 }, // 10
	{ .start = 6, .end = 7 }, // 11
	{ .start = 7, .end = 8 }, // 12
	{ .start = 8, .end = 9 }, // 13
	{ .start = 9, .end = 10 }, // 14
	{ .start = 10, .end = 11 }, // 15
};
const uint8_t Pixel_LED_FadePeriod_Defaults[4][4] = {
	{ 0, 0, 0, 0, }, // KLL_LED_FadeDefaultConfig0
	{ 0, 0, 0, 0, }, // KLL_LED_FadeDefaultConfig1
	{ 0, 0, 0, 0, }, // KLL_LED_FadeDefaultConfig2
	{ 0, 0, 0, 0, }, // KLL_LED_FadeDefaultConfig3
};


// Pixel Mapping
const PixelElement Pixel_Mapping[] = {
	{ 8, 1, {0} }, // P[['001']](0:8)
	{ 8, 1, {16} }, // P[['002']](16:8)
	{ 8, 1, {32} }, // P[['003']](32:8)
	{ 8, 1, {48} }, // P[['004']](48:8)
	{ 8, 1, {64} }, // P[['005']](64:8)
	{ 8, 1, {1} }, // P[['006']](1:8)
	{ 8, 1, {17} }, // P[['007']](17:8)
	{ 8, 1, {33} }, // P[['008']](33:8)
	{ 8, 1, {49} }, // P[['009']](49:8)
	{ 8, 1, {65} }, // P[['010']](65:8)
	{ 8, 1, {2} }, // P[['011']](2:8)
	{ 8, 1, {18} }, // P[['012']](18:8)
	{ 8, 1, {34} }, // P[['013']](34:8)
	{ 8, 1, {50} }, // P[['014']](50:8)
	{ 8, 1, {66} }, // P[['015']](66:8)
	{ 8, 1, {3} }, // P[['016']](3:8)
	{ 8, 1, {19} }, // P[['017']](19:8)
	{ 8, 1, {35} }, // P[['018']](35:8)
	{ 8, 1, {51} }, // P[['019']](51:8)
	{ 8, 1, {67} }, // P[['020']](67:8)
	{ 8, 1, {4} }, // P[['021']](4:8)
	{ 8, 1, {20} }, // P[['022']](20:8)
	{ 8, 1, {36} }, // P[['023']](36:8)
	{ 8, 1, {52} }, // P[['024']](52:8)
	{ 8, 1, {68} }, // P[['025']](68:8)
	{ 8, 1, {5} }, // P[['026']](5:8)
	{ 8, 1, {21} }, // P[['027']](21:8)
	{ 8, 1, {37} }, // P[['028']](37:8)
	{ 8, 1, {53} }, // P[['029']](53:8)
	{ 8, 1, {69} }, // P[['030']](69:8)
	{ 8, 1, {6} }, // P[['031']](6:8)
	{ 8, 1, {22} }, // P[['032']](22:8)
	{ 8, 1, {38} }, // P[['033']](38:8)
	{ 8, 1, {54} }, // P[['034']](54:8)
	{ 8, 1, {7} }, // P[['035']](7:8)
	{ 8, 1, {23} }, // P[['036']](23:8)
	{ 8, 1, {39} }, // P[['037']](39:8)
	{ 8, 1, {55} }, // P[['038']](55:8)
};


// Pixel Display Mapping
// TODO type should be determined by Pixel_TotalPixels
const uint16_t Pixel_DisplayMapping[] = {
  0,  0,  0,  0,  1,  0,  2,  0,  3,  0,  4,  0,  5,  0,  6,  0,  7,
  0,  0,  0,  0,  8,  0,  9,  0, 10,  0, 11,  0, 12,  0, 13,  0, 14,
  0,  0,  0,  0,  0,  0, 15,  0, 16,  0, 17,  0, 18,  0, 19,  0, 20,
  0,  0,  0,  0, 23,  0, 24,  0, 25,  0, 26,  0, 27,  0, 28,  0, 29,
 21,  0, 22,  0,  0,  0,  0,  0, 34,  0, 35,  0, 36,  0, 37, 38,  0,
  0, 30,  0, 32,  0, 33,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
  0,  0, 31,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
};


// Animation Frames and Framesets
//  uint8_t *<animation>_frames[] = { <animation>_frame<num>, ... }
// A[all_on, 1] <= P[c:0.0%](255), P[c:100.0%](255);
const uint8_t all_on_frame1[] = {
	PixelAddressType_ColumnFill, /*0.0*/0,0, /*None*/0,0, PixelChange_Set, 255,
	PixelAddressType_ColumnFill, /*1.0*/16,0, /*None*/0,0, PixelChange_Set, 255,
	PixelAddressType_End
};

//// all_on Animation Frame Set ////
const uint8_t *all_on_frames[] = {
	all_on_frame1,
	0
};



// Index of animations
//  uint8_t *Pixel_Animations[] = { <animation>_frames, ... }
const uint8_t **Pixel_Animations[] = {
	/*0*/ all_on_frames,
};
// Animation Settings
//  const AnimationStackElement AnimationSettings[] = {
//    { <triggerguide>, <index>, <pos>, <subpos>, <loops>, <framedelay>, <frameoption>, <ffunc>, <pfunc>, <replace>, <state> }, ...
//  }
const AnimationStackElement Pixel_AnimationSettings[] = {
	{ (TriggerMacro*)1, Animation__all_on, /*0 pfunc:interp,start*/
		0, 0, 0, 0, PixelFrameOption_None, 0, 1, 0, AnimationPlayState_Start},

	/* Additional Settings */

};


// ScanCode to Pixel Mapping
const uint16_t Pixel_ScanCodeToPixel[] = {
	/*1*/ 0,
	/*2*/ 0,
	/*3*/ 1, // P[['001']](0:8)
	/*4*/ 2, // P[['002']](16:8)
	/*5*/ 3, // P[['003']](32:8)
	/*6*/ 4, // P[['004']](48:8)
	/*7*/ 5, // P[['005']](64:8)
	/*8*/ 6, // P[['006']](1:8)
	/*9*/ 7, // P[['007']](17:8)
	/*10*/ 0,
	/*11*/ 0,
	/*12*/ 8, // P[['008']](33:8)
	/*13*/ 9, // P[['009']](49:8)
	/*14*/ 10, // P[['010']](65:8)
	/*15*/ 11, // P[['011']](2:8)
	/*16*/ 12, // P[['012']](18:8)
	/*17*/ 13, // P[['013']](34:8)
	/*18*/ 14, // P[['014']](50:8)
	/*19*/ 0,
	/*20*/ 0,
	/*21*/ 0,
	/*22*/ 15, // P[['015']](66:8)
	/*23*/ 16, // P[['016']](3:8)
	/*24*/ 17, // P[['017']](19:8)
	/*25*/ 18, // P[['018']](35:8)
	/*26*/ 19, // P[['019']](51:8)
	/*27*/ 20, // P[['020']](67:8)
	/*28*/ 21, // P[['021']](4:8)
	/*29*/ 22, // P[['022']](20:8)
	/*30*/ 23, // P[['023']](36:8)
	/*31*/ 24, // P[['024']](52:8)
	/*32*/ 25, // P[['025']](68:8)
	/*33*/ 26, // P[['026']](5:8)
	/*34*/ 27, // P[['027']](21:8)
	/*35*/ 28, // P[['028']](37:8)
	/*36*/ 29, // P[['029']](53:8)
	/*37*/ 30, // P[['030']](69:8)
	/*38*/ 31, // P[['031']](6:8)
	/*39*/ 32, // P[['032']](22:8)
	/*40*/ 33, // P[['033']](38:8)
	/*41*/ 34, // P[['034']](54:8)
	/*42*/ 35, // P[['035']](7:8)
	/*43*/ 36, // P[['036']](23:8)
	/*44*/ 37, // P[['037']](39:8)
	/*45*/ 38, // P[['038']](55:8)
};


// ScanCode to Display Mapping
const uint16_t Pixel_ScanCodeToDisplay[] = {
	/*__,__ 1*/ 0,
	/*__,__ 2*/ 0,
	/* 4, 0 3*/ 4, // P[['001']](0:8)
	/* 6, 0 4*/ 6, // P[['002']](16:8)
	/* 8, 0 5*/ 8, // P[['003']](32:8)
	/*10, 0 6*/ 10, // P[['004']](48:8)
	/*12, 0 7*/ 12, // P[['005']](64:8)
	/*14, 0 8*/ 14, // P[['006']](1:8)
	/*16, 0 9*/ 16, // P[['007']](17:8)
	/*__,__ 10*/ 0,
	/*__,__ 11*/ 0,
	/* 4, 1 12*/ 21, // P[['008']](33:8)
	/* 6, 1 13*/ 23, // P[['009']](49:8)
	/* 8, 1 14*/ 25, // P[['010']](65:8)
	/*10, 1 15*/ 27, // P[['011']](2:8)
	/*12, 1 16*/ 29, // P[['012']](18:8)
	/*14, 1 17*/ 31, // P[['013']](34:8)
	/*16, 1 18*/ 33, // P[['014']](50:8)
	/*__,__ 19*/ 0,
	/*__,__ 20*/ 0,
	/*__,__ 21*/ 0,
	/* 6, 2 22*/ 40, // P[['015']](66:8)
	/* 8, 2 23*/ 42, // P[['016']](3:8)
	/*10, 2 24*/ 44, // P[['017']](19:8)
	/*12, 2 25*/ 46, // P[['018']](35:8)
	/*14, 2 26*/ 48, // P[['019']](51:8)
	/*16, 2 27*/ 50, // P[['020']](67:8)
	/* 0, 4 28*/ 68, // P[['021']](4:8)
	/* 2, 4 29*/ 70, // P[['022']](20:8)
	/* 4, 3 30*/ 55, // P[['023']](36:8)
	/* 6, 3 31*/ 57, // P[['024']](52:8)
	/* 8, 3 32*/ 59, // P[['025']](68:8)
	/*10, 3 33*/ 61, // P[['026']](5:8)
	/*12, 3 34*/ 63, // P[['027']](21:8)
	/*14, 3 35*/ 65, // P[['028']](37:8)
	/*16, 3 36*/ 67, // P[['029']](53:8)
	/* 1, 5 37*/ 86, // P[['030']](69:8)
	/* 2, 6 38*/ 104, // P[['031']](6:8)
	/* 3, 5 39*/ 88, // P[['032']](22:8)
	/* 5, 5 40*/ 90, // P[['033']](38:8)
	/* 8, 4 41*/ 76, // P[['034']](54:8)
	/*10, 4 42*/ 78, // P[['035']](7:8)
	/*12, 4 43*/ 80, // P[['036']](23:8)
	/*14, 4 44*/ 82, // P[['037']](39:8)
	/*15, 4 45*/ 83, // P[['038']](55:8)
};

