/* Copyright (C) 2014-2018 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2018-11-17
// KLL Emitter:        kiibohd
// KLL Version:        0.5.6.6
// KLL Git Changes:    None
// Compiler arguments:
//    /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/__main__.py
//    --kiibohd-debug
//    --config
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Devices/ISSILed/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Devices/MatrixARMPeriodic/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Devices/STLcd/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Devices/UARTConnect/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Macro/PartialMap/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Macro/PixelMap/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Output/HID-IO/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Output/USB/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Debug/latency/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Debug/led/capabilities.kll
//    --base
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/scancode_map.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/rightHand.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/slave1.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/leftHand.kll
//    --default
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/infinity_ergodox/all-leds.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/infinity_ergodox/mdergo1Overlay.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/infinity_ergodox/lcdFuncMap.kll
//    --partial
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/infinity_ergodox/iced_func.kll
//    --partial
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/infinity_ergodox/iced_numpad.kll
//    --emitter
//      kiibohd
//    --def-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/kll_defs.h
//    --map-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/generatedKeymap.h
//    --hid-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/usb_hid.h
//    --pixel-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/generatedPixelmap.c
//    --json-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/kll.json
//
// - Configuration File -
//    ISSILedCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll
//    MatrixARMPeriodicCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll
//    STLcdCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Devices_STLcd@['capabilities']_processed.kll
//    UARTConnectCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Devices_UARTConnect@['capabilities']_processed.kll
//    PartialMapCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Macro_PartialMap@['capabilities']_processed.kll
//    PixelMapCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Macro_PixelMap@['capabilities']_processed.kll
//    HID-IOCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Output_HID-IO@['capabilities']_processed.kll
//    USBCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Output_USB@['capabilities']_processed.kll
//    latency
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Debug_latency@['capabilities']_processed.kll
//    led
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Debug_led@['capabilities']_processed.kll
// - Generic Files -
// - Base Layer -
//    Infinity_Ergodox
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['scancode_map']_processed.kll
//    Infinity Ergodox Right Hand
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['rightHand']_processed.kll
//    MDErgo1Slave1
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['slave1']_processed.kll
//    Infinity Ergodox Left Hand
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['leftHand']_processed.kll
// - Default Layer -
//    all-leds
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/.local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['all-leds']_processed.kll
//    mdergo1Overlay
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/.local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['mdergo1Overlay']_processed.kll
//    lcdFuncMap
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/.local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll
// - Partial Layers -
//    Layer 1
//     ICEDFunctionLayer
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/.local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['iced_func']_processed.kll
//    Layer 2
//     ICEDNumpadLayer
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/.local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['iced_numpad']_processed.kll



#pragma once

// ----- Includes -----

// KLL Include
#include <kll.h>



// ----- Capabilities -----

// Capability function declarations
void LCD_layerStackExact_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void LCD_layerStack_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void LED_control_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerLatch_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerLock_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerRotate_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerShift_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Layer_layerState_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_none_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_rotate_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_testThreadSafe_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_testThreadUnsafe_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_consCtrlSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_flashMode_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_kbdProtocolBoot_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_kbdProtocolNKRO_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_noneSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_sysCtrlSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_toggleKbdProtocol_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbCodeSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbMouseWheel_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbMouse_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_AnimationControl_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_AnimationIndex_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_Animation_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_FadeLayerHighlight_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_FadeSet_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_Pixel_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );



// Indexed Capabilities Table
const Capability CapabilitiesList[] = {
	/* 0 LCDLayerDisplayExact */
	{ LCD_layerStackExact_capability, 9, CapabilityFeature_None },
	/* 1 LCDLayerDisplay */
	{ LCD_layerStack_capability, 0, CapabilityFeature_None },
	/* 2 ledControl */
	{ LED_control_capability, 2, CapabilityFeature_None },
	/* 3 layerLatch */
	{ Layer_layerLatch_capability, 2, CapabilityFeature_Safe },
	/* 4 layerLock */
	{ Layer_layerLock_capability, 2, CapabilityFeature_Safe },
	/* 5 layerRotate */
	{ Layer_layerRotate_capability, 1, CapabilityFeature_Safe },
	/* 6 layerShift */
	{ Layer_layerShift_capability, 2, CapabilityFeature_Safe },
	/* 7 layerState */
	{ Layer_layerState_capability, 3, CapabilityFeature_Safe },
	/* 8 none */
	{ Macro_none_capability, 0, CapabilityFeature_None },
	/* 9 rotate */
	{ Macro_rotate_capability, 2, CapabilityFeature_None },
	/* 10 testThreadSafe */
	{ Macro_testThreadSafe_capability, 0, CapabilityFeature_Safe },
	/* 11 testThreadUnsafe */
	{ Macro_testThreadUnsafe_capability, 0, CapabilityFeature_None },
	/* 12 consCtrlOut */
	{ Output_consCtrlSend_capability, 2, CapabilityFeature_Safe },
	/* 13 flashMode */
	{ Output_flashMode_capability, 0, CapabilityFeature_Safe },
	/* 14 kbdProtocolBoot */
	{ Output_kbdProtocolBoot_capability, 0, CapabilityFeature_None },
	/* 15 kbdProtocolNKRO */
	{ Output_kbdProtocolNKRO_capability, 0, CapabilityFeature_None },
	/* 16 noneOut */
	{ Output_noneSend_capability, 0, CapabilityFeature_Safe },
	/* 17 sysCtrlOut */
	{ Output_sysCtrlSend_capability, 1, CapabilityFeature_Safe },
	/* 18 toggleKbdProtocol */
	{ Output_toggleKbdProtocol_capability, 0, CapabilityFeature_None },
	/* 19 usbKeyOut */
	{ Output_usbCodeSend_capability, 1, CapabilityFeature_Safe },
	/* 20 mouseWheelOut */
	{ Output_usbMouseWheel_capability, 2, CapabilityFeature_Safe },
	/* 21 mouseOut */
	{ Output_usbMouse_capability, 6, CapabilityFeature_Safe },
	/* 22 animation_control */
	{ Pixel_AnimationControl_capability, 1, CapabilityFeature_None },
	/* 23 animationIndex */
	{ Pixel_AnimationIndex_capability, 2, CapabilityFeature_None },
	/* 24 animation */
	{ Pixel_Animation_capability, 7, CapabilityFeature_None },
	/* 25 fade_layer_highlight */
	{ Pixel_FadeLayerHighlight_capability, 2, CapabilityFeature_None },
	/* 26 fade_set */
	{ Pixel_FadeSet_capability, 3, CapabilityFeature_None },
	/* 27 pixel */
	{ Pixel_Pixel_capability, 0, CapabilityFeature_None },
};


// -- Result Macros

// Result Macro Guides
Guide_RM( 0 ) = { 1, 19, KEY_A_4, 0 }; // (HID(USBCode,default)"4"A)
Guide_RM( 1 ) = { 1, 19, KEY_B_5, 0 }; // (HID(USBCode,default)"5"B)
Guide_RM( 2 ) = { 1, 19, KEY_C_6, 0 }; // (HID(USBCode,default)"6"C)
Guide_RM( 3 ) = { 1, 19, KEY_D_7, 0 }; // (HID(USBCode,default)"7"D)
Guide_RM( 4 ) = { 1, 19, KEY_E_8, 0 }; // (HID(USBCode,default)"8"E)
Guide_RM( 5 ) = { 1, 19, KEY_F_9, 0 }; // (HID(USBCode,default)"9"F)
Guide_RM( 6 ) = { 1, 19, KEY_G_10, 0 }; // (HID(USBCode,default)"10"G)
Guide_RM( 7 ) = { 1, 19, KEY_H_11, 0 }; // (HID(USBCode,default)"11"H)
Guide_RM( 8 ) = { 1, 19, KEY_I_12, 0 }; // (HID(USBCode,default)"12"I)
Guide_RM( 9 ) = { 1, 19, KEY_J_13, 0 }; // (HID(USBCode,default)"13"J)
Guide_RM( 10 ) = { 1, 19, KEY_K_14, 0 }; // (HID(USBCode,default)"14"K)
Guide_RM( 11 ) = { 1, 19, KEY_L_15, 0 }; // (HID(USBCode,default)"15"L)
Guide_RM( 12 ) = { 1, 19, KEY_M_16, 0 }; // (HID(USBCode,default)"16"M)
Guide_RM( 13 ) = { 1, 19, KEY_N_17, 0 }; // (HID(USBCode,default)"17"N)
Guide_RM( 14 ) = { 1, 19, KEY_O_18, 0 }; // (HID(USBCode,default)"18"O)
Guide_RM( 15 ) = { 1, 19, KEY_P_19, 0 }; // (HID(USBCode,default)"19"P)
Guide_RM( 16 ) = { 1, 19, KEY_Q_20, 0 }; // (HID(USBCode,default)"20"Q)
Guide_RM( 17 ) = { 1, 19, KEY_R_21, 0 }; // (HID(USBCode,default)"21"R)
Guide_RM( 18 ) = { 1, 19, KEY_S_22, 0 }; // (HID(USBCode,default)"22"S)
Guide_RM( 19 ) = { 1, 19, KEY_T_23, 0 }; // (HID(USBCode,default)"23"T)
Guide_RM( 20 ) = { 1, 19, KEY_U_24, 0 }; // (HID(USBCode,default)"24"U)
Guide_RM( 21 ) = { 1, 19, KEY_V_25, 0 }; // (HID(USBCode,default)"25"V)
Guide_RM( 22 ) = { 1, 19, KEY_W_26, 0 }; // (HID(USBCode,default)"26"W)
Guide_RM( 23 ) = { 1, 19, KEY_X_27, 0 }; // (HID(USBCode,default)"27"X)
Guide_RM( 24 ) = { 1, 19, KEY_Y_28, 0 }; // (HID(USBCode,default)"28"Y)
Guide_RM( 25 ) = { 1, 19, KEY_Z_29, 0 }; // (HID(USBCode,default)"29"Z)
Guide_RM( 26 ) = { 1, 19, KEY_1_30, 0 }; // (HID(USBCode,default)"30"1)
Guide_RM( 27 ) = { 1, 19, KEY_2_31, 0 }; // (HID(USBCode,default)"31"2)
Guide_RM( 28 ) = { 1, 19, KEY_3_32, 0 }; // (HID(USBCode,default)"32"3)
Guide_RM( 29 ) = { 1, 19, KEY_4_33, 0 }; // (HID(USBCode,default)"33"4)
Guide_RM( 30 ) = { 1, 19, KEY_5_34, 0 }; // (HID(USBCode,default)"34"5)
Guide_RM( 31 ) = { 1, 19, KEY_6_35, 0 }; // (HID(USBCode,default)"35"6)
Guide_RM( 32 ) = { 1, 19, KEY_7_36, 0 }; // (HID(USBCode,default)"36"7)
Guide_RM( 33 ) = { 1, 19, KEY_8_37, 0 }; // (HID(USBCode,default)"37"8)
Guide_RM( 34 ) = { 1, 19, KEY_9_38, 0 }; // (HID(USBCode,default)"38"9)
Guide_RM( 35 ) = { 1, 19, KEY_0_39, 0 }; // (HID(USBCode,default)"39"0)
Guide_RM( 36 ) = { 1, 19, KEY_ENTER_40, 0 }; // (HID(USBCode,default)"40"Enter)
Guide_RM( 37 ) = { 1, 19, KEY_ESC_41, 0 }; // (HID(USBCode,default)"41"Esc)
Guide_RM( 38 ) = { 1, 19, KEY_BACKSPACE_42, 0 }; // (HID(USBCode,default)"42"Backspace)
Guide_RM( 39 ) = { 1, 19, KEY_TAB_43, 0 }; // (HID(USBCode,default)"43"Tab)
Guide_RM( 40 ) = { 1, 19, KEY_SPACE_44, 0 }; // (HID(USBCode,default)"44"Space)
Guide_RM( 41 ) = { 1, 19, KEY_MINUS_45, 0 }; // (HID(USBCode,default)"45"Minus)
Guide_RM( 42 ) = { 1, 19, KEY_EQUAL_46, 0 }; // (HID(USBCode,default)"46"Equal)
Guide_RM( 43 ) = { 1, 19, KEY_LEFT_BRACKET_47, 0 }; // (HID(USBCode,default)"47"Left Bracket)
Guide_RM( 44 ) = { 1, 19, KEY_RIGHT_BRACKET_48, 0 }; // (HID(USBCode,default)"48"Right Bracket)
Guide_RM( 45 ) = { 1, 19, KEY_BACKSLASH_49, 0 }; // (HID(USBCode,default)"49"Backslash)
Guide_RM( 46 ) = { 1, 19, KEY_SEMICOLON_51, 0 }; // (HID(USBCode,default)"51"Semicolon)
Guide_RM( 47 ) = { 1, 19, KEY_QUOTE_52, 0 }; // (HID(USBCode,default)"52"Quote)
Guide_RM( 48 ) = { 1, 19, KEY_BACKTICK_53, 0 }; // (HID(USBCode,default)"53"Backtick)
Guide_RM( 49 ) = { 1, 19, KEY_COMMA_54, 0 }; // (HID(USBCode,default)"54"Comma)
Guide_RM( 50 ) = { 1, 19, KEY_PERIOD_55, 0 }; // (HID(USBCode,default)"55"Period)
Guide_RM( 51 ) = { 1, 19, KEY_SLASH_56, 0 }; // (HID(USBCode,default)"56"Slash)
Guide_RM( 52 ) = { 1, 19, KEY_F1_58, 0 }; // (HID(USBCode,default)"58"F1)
Guide_RM( 53 ) = { 1, 19, KEY_F2_59, 0 }; // (HID(USBCode,default)"59"F2)
Guide_RM( 54 ) = { 1, 19, KEY_F3_60, 0 }; // (HID(USBCode,default)"60"F3)
Guide_RM( 55 ) = { 1, 19, KEY_F4_61, 0 }; // (HID(USBCode,default)"61"F4)
Guide_RM( 56 ) = { 1, 19, KEY_F5_62, 0 }; // (HID(USBCode,default)"62"F5)
Guide_RM( 57 ) = { 1, 19, KEY_F6_63, 0 }; // (HID(USBCode,default)"63"F6)
Guide_RM( 58 ) = { 1, 19, KEY_F7_64, 0 }; // (HID(USBCode,default)"64"F7)
Guide_RM( 59 ) = { 1, 19, KEY_F8_65, 0 }; // (HID(USBCode,default)"65"F8)
Guide_RM( 60 ) = { 1, 19, KEY_F9_66, 0 }; // (HID(USBCode,default)"66"F9)
Guide_RM( 61 ) = { 1, 19, KEY_F10_67, 0 }; // (HID(USBCode,default)"67"F10)
Guide_RM( 62 ) = { 1, 19, KEY_F11_68, 0 }; // (HID(USBCode,default)"68"F11)
Guide_RM( 63 ) = { 1, 19, KEY_F12_69, 0 }; // (HID(USBCode,default)"69"F12)
Guide_RM( 64 ) = { 1, 19, KEY_HOME_74, 0 }; // (HID(USBCode,default)"74"Home)
Guide_RM( 65 ) = { 1, 19, KEY_PAGE_UP_75, 0 }; // (HID(USBCode,default)"75"Page Up)
Guide_RM( 66 ) = { 1, 19, KEY_DELETE_76, 0 }; // (HID(USBCode,default)"76"Delete)
Guide_RM( 67 ) = { 1, 19, KEY_END_77, 0 }; // (HID(USBCode,default)"77"End)
Guide_RM( 68 ) = { 1, 19, KEY_PAGE_DOWN_78, 0 }; // (HID(USBCode,default)"78"Page Down)
Guide_RM( 69 ) = { 1, 19, KEY_RIGHT_79, 0 }; // (HID(USBCode,default)"79"Right)
Guide_RM( 70 ) = { 1, 19, KEY_LEFT_80, 0 }; // (HID(USBCode,default)"80"Left)
Guide_RM( 71 ) = { 1, 19, KEY_DOWN_81, 0 }; // (HID(USBCode,default)"81"Down)
Guide_RM( 72 ) = { 1, 19, KEY_UP_82, 0 }; // (HID(USBCode,default)"82"Up)
Guide_RM( 73 ) = { 1, 19, KEY_NUM_LOCK_83, 0 }; // (HID(USBCode,default)"83"Num Lock)
Guide_RM( 74 ) = { 1, 19, KEY_KEYPAD_SLASH_84, 0 }; // (HID(USBCode,default)"84"Keypad Slash)
Guide_RM( 75 ) = { 1, 19, KEY_KEYPAD_ASTERISK_85, 0 }; // (HID(USBCode,default)"85"Keypad Asterisk)
Guide_RM( 76 ) = { 1, 19, KEY_KEYPAD_MINUS_86, 0 }; // (HID(USBCode,default)"86"Keypad Minus)
Guide_RM( 77 ) = { 1, 19, KEY_KEYPAD_PLUS_87, 0 }; // (HID(USBCode,default)"87"Keypad Plus)
Guide_RM( 78 ) = { 1, 19, KEY_KEYPAD_ENTER_88, 0 }; // (HID(USBCode,default)"88"Keypad Enter)
Guide_RM( 79 ) = { 1, 19, KEY_KEYPAD_1_89, 0 }; // (HID(USBCode,default)"89"Keypad 1)
Guide_RM( 80 ) = { 1, 19, KEY_KEYPAD_2_90, 0 }; // (HID(USBCode,default)"90"Keypad 2)
Guide_RM( 81 ) = { 1, 19, KEY_KEYPAD_3_91, 0 }; // (HID(USBCode,default)"91"Keypad 3)
Guide_RM( 82 ) = { 1, 19, KEY_KEYPAD_4_92, 0 }; // (HID(USBCode,default)"92"Keypad 4)
Guide_RM( 83 ) = { 1, 19, KEY_KEYPAD_5_93, 0 }; // (HID(USBCode,default)"93"Keypad 5)
Guide_RM( 84 ) = { 1, 19, KEY_KEYPAD_6_94, 0 }; // (HID(USBCode,default)"94"Keypad 6)
Guide_RM( 85 ) = { 1, 19, KEY_KEYPAD_7_95, 0 }; // (HID(USBCode,default)"95"Keypad 7)
Guide_RM( 86 ) = { 1, 19, KEY_KEYPAD_8_96, 0 }; // (HID(USBCode,default)"96"Keypad 8)
Guide_RM( 87 ) = { 1, 19, KEY_KEYPAD_9_97, 0 }; // (HID(USBCode,default)"97"Keypad 9)
Guide_RM( 88 ) = { 1, 19, KEY_KEYPAD_0_98, 0 }; // (HID(USBCode,default)"98"Keypad 0)
Guide_RM( 89 ) = { 1, 19, KEY_KEYPAD_PERIOD_99, 0 }; // (HID(USBCode,default)"99"Keypad Period)
Guide_RM( 90 ) = { 1, 19, KEY_LEFT_CONTROL_224, 0 }; // (HID(USBCode,default)"224"Left Control)
Guide_RM( 91 ) = { 1, 19, KEY_LEFT_SHIFT_225, 0 }; // (HID(USBCode,default)"225"Left Shift)
Guide_RM( 92 ) = { 1, 19, KEY_LEFT_ALT_226, 0 }; // (HID(USBCode,default)"226"Left Alt)
Guide_RM( 93 ) = { 1, 19, KEY_LEFT_GUI_227, 0 }; // (HID(USBCode,default)"227"Left GUI)
Guide_RM( 94 ) = { 1, 19, KEY_RIGHT_CONTROL_228, 0 }; // (HID(USBCode,default)"228"Right Control)
Guide_RM( 95 ) = { 1, 19, KEY_RIGHT_SHIFT_229, 0 }; // (HID(USBCode,default)"229"Right Shift)
Guide_RM( 96 ) = { 1, 19, KEY_RIGHT_ALT_230, 0 }; // (HID(USBCode,default)"230"Right Alt)
Guide_RM( 97 ) = { 1, 19, KEY_RIGHT_GUI_231, 0 }; // (HID(USBCode,default)"231"Right GUI)
Guide_RM( 98 ) = { 1, 13, 0 }; // (flashMode())
Guide_RM( 99 ) = { 2, 4, 1, 0, 1, 0 }; // (layerLock(1) + LCDLayerDisplay())
Guide_RM( 100 ) = { 2, 4, 2, 0, 1, 0 }; // (layerLock(2) + LCDLayerDisplay())
Guide_RM( 101 ) = { 2, 6, 1, 0, 1, 0 }; // (layerShift(1) + LCDLayerDisplay())


// -- Result Macro List

// Indexed Table of Result Macros
const ResultMacro ResultMacroList[] = {
	Define_RM( 0 ), // (HID(USBCode,default)"4"A)
	Define_RM( 1 ), // (HID(USBCode,default)"5"B)
	Define_RM( 2 ), // (HID(USBCode,default)"6"C)
	Define_RM( 3 ), // (HID(USBCode,default)"7"D)
	Define_RM( 4 ), // (HID(USBCode,default)"8"E)
	Define_RM( 5 ), // (HID(USBCode,default)"9"F)
	Define_RM( 6 ), // (HID(USBCode,default)"10"G)
	Define_RM( 7 ), // (HID(USBCode,default)"11"H)
	Define_RM( 8 ), // (HID(USBCode,default)"12"I)
	Define_RM( 9 ), // (HID(USBCode,default)"13"J)
	Define_RM( 10 ), // (HID(USBCode,default)"14"K)
	Define_RM( 11 ), // (HID(USBCode,default)"15"L)
	Define_RM( 12 ), // (HID(USBCode,default)"16"M)
	Define_RM( 13 ), // (HID(USBCode,default)"17"N)
	Define_RM( 14 ), // (HID(USBCode,default)"18"O)
	Define_RM( 15 ), // (HID(USBCode,default)"19"P)
	Define_RM( 16 ), // (HID(USBCode,default)"20"Q)
	Define_RM( 17 ), // (HID(USBCode,default)"21"R)
	Define_RM( 18 ), // (HID(USBCode,default)"22"S)
	Define_RM( 19 ), // (HID(USBCode,default)"23"T)
	Define_RM( 20 ), // (HID(USBCode,default)"24"U)
	Define_RM( 21 ), // (HID(USBCode,default)"25"V)
	Define_RM( 22 ), // (HID(USBCode,default)"26"W)
	Define_RM( 23 ), // (HID(USBCode,default)"27"X)
	Define_RM( 24 ), // (HID(USBCode,default)"28"Y)
	Define_RM( 25 ), // (HID(USBCode,default)"29"Z)
	Define_RM( 26 ), // (HID(USBCode,default)"30"1)
	Define_RM( 27 ), // (HID(USBCode,default)"31"2)
	Define_RM( 28 ), // (HID(USBCode,default)"32"3)
	Define_RM( 29 ), // (HID(USBCode,default)"33"4)
	Define_RM( 30 ), // (HID(USBCode,default)"34"5)
	Define_RM( 31 ), // (HID(USBCode,default)"35"6)
	Define_RM( 32 ), // (HID(USBCode,default)"36"7)
	Define_RM( 33 ), // (HID(USBCode,default)"37"8)
	Define_RM( 34 ), // (HID(USBCode,default)"38"9)
	Define_RM( 35 ), // (HID(USBCode,default)"39"0)
	Define_RM( 36 ), // (HID(USBCode,default)"40"Enter)
	Define_RM( 37 ), // (HID(USBCode,default)"41"Esc)
	Define_RM( 38 ), // (HID(USBCode,default)"42"Backspace)
	Define_RM( 39 ), // (HID(USBCode,default)"43"Tab)
	Define_RM( 40 ), // (HID(USBCode,default)"44"Space)
	Define_RM( 41 ), // (HID(USBCode,default)"45"Minus)
	Define_RM( 42 ), // (HID(USBCode,default)"46"Equal)
	Define_RM( 43 ), // (HID(USBCode,default)"47"Left Bracket)
	Define_RM( 44 ), // (HID(USBCode,default)"48"Right Bracket)
	Define_RM( 45 ), // (HID(USBCode,default)"49"Backslash)
	Define_RM( 46 ), // (HID(USBCode,default)"51"Semicolon)
	Define_RM( 47 ), // (HID(USBCode,default)"52"Quote)
	Define_RM( 48 ), // (HID(USBCode,default)"53"Backtick)
	Define_RM( 49 ), // (HID(USBCode,default)"54"Comma)
	Define_RM( 50 ), // (HID(USBCode,default)"55"Period)
	Define_RM( 51 ), // (HID(USBCode,default)"56"Slash)
	Define_RM( 52 ), // (HID(USBCode,default)"58"F1)
	Define_RM( 53 ), // (HID(USBCode,default)"59"F2)
	Define_RM( 54 ), // (HID(USBCode,default)"60"F3)
	Define_RM( 55 ), // (HID(USBCode,default)"61"F4)
	Define_RM( 56 ), // (HID(USBCode,default)"62"F5)
	Define_RM( 57 ), // (HID(USBCode,default)"63"F6)
	Define_RM( 58 ), // (HID(USBCode,default)"64"F7)
	Define_RM( 59 ), // (HID(USBCode,default)"65"F8)
	Define_RM( 60 ), // (HID(USBCode,default)"66"F9)
	Define_RM( 61 ), // (HID(USBCode,default)"67"F10)
	Define_RM( 62 ), // (HID(USBCode,default)"68"F11)
	Define_RM( 63 ), // (HID(USBCode,default)"69"F12)
	Define_RM( 64 ), // (HID(USBCode,default)"74"Home)
	Define_RM( 65 ), // (HID(USBCode,default)"75"Page Up)
	Define_RM( 66 ), // (HID(USBCode,default)"76"Delete)
	Define_RM( 67 ), // (HID(USBCode,default)"77"End)
	Define_RM( 68 ), // (HID(USBCode,default)"78"Page Down)
	Define_RM( 69 ), // (HID(USBCode,default)"79"Right)
	Define_RM( 70 ), // (HID(USBCode,default)"80"Left)
	Define_RM( 71 ), // (HID(USBCode,default)"81"Down)
	Define_RM( 72 ), // (HID(USBCode,default)"82"Up)
	Define_RM( 73 ), // (HID(USBCode,default)"83"Num Lock)
	Define_RM( 74 ), // (HID(USBCode,default)"84"Keypad Slash)
	Define_RM( 75 ), // (HID(USBCode,default)"85"Keypad Asterisk)
	Define_RM( 76 ), // (HID(USBCode,default)"86"Keypad Minus)
	Define_RM( 77 ), // (HID(USBCode,default)"87"Keypad Plus)
	Define_RM( 78 ), // (HID(USBCode,default)"88"Keypad Enter)
	Define_RM( 79 ), // (HID(USBCode,default)"89"Keypad 1)
	Define_RM( 80 ), // (HID(USBCode,default)"90"Keypad 2)
	Define_RM( 81 ), // (HID(USBCode,default)"91"Keypad 3)
	Define_RM( 82 ), // (HID(USBCode,default)"92"Keypad 4)
	Define_RM( 83 ), // (HID(USBCode,default)"93"Keypad 5)
	Define_RM( 84 ), // (HID(USBCode,default)"94"Keypad 6)
	Define_RM( 85 ), // (HID(USBCode,default)"95"Keypad 7)
	Define_RM( 86 ), // (HID(USBCode,default)"96"Keypad 8)
	Define_RM( 87 ), // (HID(USBCode,default)"97"Keypad 9)
	Define_RM( 88 ), // (HID(USBCode,default)"98"Keypad 0)
	Define_RM( 89 ), // (HID(USBCode,default)"99"Keypad Period)
	Define_RM( 90 ), // (HID(USBCode,default)"224"Left Control)
	Define_RM( 91 ), // (HID(USBCode,default)"225"Left Shift)
	Define_RM( 92 ), // (HID(USBCode,default)"226"Left Alt)
	Define_RM( 93 ), // (HID(USBCode,default)"227"Left GUI)
	Define_RM( 94 ), // (HID(USBCode,default)"228"Right Control)
	Define_RM( 95 ), // (HID(USBCode,default)"229"Right Shift)
	Define_RM( 96 ), // (HID(USBCode,default)"230"Right Alt)
	Define_RM( 97 ), // (HID(USBCode,default)"231"Right GUI)
	Define_RM( 98 ), // (flashMode())
	Define_RM( 99 ), // (layerLock(1) + LCDLayerDisplay())
	Define_RM( 100 ), // (layerLock(2) + LCDLayerDisplay())
	Define_RM( 101 ), // (layerShift(1) + LCDLayerDisplay())
};


// -- Trigger Macros

// Trigger Macro Guides
Guide_TM( 0 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x03, 0 }; // (S003)
Guide_TM( 1 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x04, 0 }; // (S004)
Guide_TM( 2 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x05, 0 }; // (S005)
Guide_TM( 3 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x06, 0 }; // (S006)
Guide_TM( 4 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x07, 0 }; // (S007)
Guide_TM( 5 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x08, 0 }; // (S008)
Guide_TM( 6 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x09, 0 }; // (S009)
Guide_TM( 7 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x0C, 0 }; // (S012)
Guide_TM( 8 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x0D, 0 }; // (S013)
Guide_TM( 9 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x0E, 0 }; // (S014)
Guide_TM( 10 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x0F, 0 }; // (S015)
Guide_TM( 11 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x10, 0 }; // (S016)
Guide_TM( 12 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x11, 0 }; // (S017)
Guide_TM( 13 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x12, 0 }; // (S018)
Guide_TM( 14 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x16, 0 }; // (S022)
Guide_TM( 15 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x17, 0 }; // (S023)
Guide_TM( 16 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x18, 0 }; // (S024)
Guide_TM( 17 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x19, 0 }; // (S025)
Guide_TM( 18 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x1A, 0 }; // (S026)
Guide_TM( 19 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x1B, 0 }; // (S027)
Guide_TM( 20 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x1C, 0 }; // (S028)
Guide_TM( 21 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x1D, 0 }; // (S029)
Guide_TM( 22 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x1E, 0 }; // (S030)
Guide_TM( 23 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x1F, 0 }; // (S031)
Guide_TM( 24 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x20, 0 }; // (S032)
Guide_TM( 25 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x21, 0 }; // (S033)
Guide_TM( 26 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x22, 0 }; // (S034)
Guide_TM( 27 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x23, 0 }; // (S035)
Guide_TM( 28 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x24, 0 }; // (S036)
Guide_TM( 29 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x25, 0 }; // (S037)
Guide_TM( 30 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x26, 0 }; // (S038)
Guide_TM( 31 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x27, 0 }; // (S039)
Guide_TM( 32 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x28, 0 }; // (S040)
Guide_TM( 33 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x29, 0 }; // (S041)
Guide_TM( 34 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x2A, 0 }; // (S042)
Guide_TM( 35 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x2B, 0 }; // (S043)
Guide_TM( 36 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x2C, 0 }; // (S044)
Guide_TM( 37 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x2D, 0 }; // (S045)
Guide_TM( 38 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x30, 0 }; // (S048)
Guide_TM( 39 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x31, 0 }; // (S049)
Guide_TM( 40 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x32, 0 }; // (S050)
Guide_TM( 41 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x33, 0 }; // (S051)
Guide_TM( 42 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x34, 0 }; // (S052)
Guide_TM( 43 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x35, 0 }; // (S053)
Guide_TM( 44 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x36, 0 }; // (S054)
Guide_TM( 45 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x39, 0 }; // (S057)
Guide_TM( 46 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x3A, 0 }; // (S058)
Guide_TM( 47 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x3B, 0 }; // (S059)
Guide_TM( 48 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x3C, 0 }; // (S060)
Guide_TM( 49 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x3D, 0 }; // (S061)
Guide_TM( 50 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x3E, 0 }; // (S062)
Guide_TM( 51 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x3F, 0 }; // (S063)
Guide_TM( 52 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x43, 0 }; // (S067)
Guide_TM( 53 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x44, 0 }; // (S068)
Guide_TM( 54 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x45, 0 }; // (S069)
Guide_TM( 55 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x46, 0 }; // (S070)
Guide_TM( 56 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x47, 0 }; // (S071)
Guide_TM( 57 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x48, 0 }; // (S072)
Guide_TM( 58 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x49, 0 }; // (S073)
Guide_TM( 59 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x4A, 0 }; // (S074)
Guide_TM( 60 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x4B, 0 }; // (S075)
Guide_TM( 61 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x4C, 0 }; // (S076)
Guide_TM( 62 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x4D, 0 }; // (S077)
Guide_TM( 63 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x4E, 0 }; // (S078)
Guide_TM( 64 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x4F, 0 }; // (S079)
Guide_TM( 65 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x50, 0 }; // (S080)
Guide_TM( 66 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x51, 0 }; // (S081)
Guide_TM( 67 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x52, 0 }; // (S082)
Guide_TM( 68 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x53, 0 }; // (S083)
Guide_TM( 69 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x54, 0 }; // (S084)
Guide_TM( 70 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x55, 0 }; // (S085)
Guide_TM( 71 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x56, 0 }; // (S086)
Guide_TM( 72 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x57, 0 }; // (S087)
Guide_TM( 73 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x58, 0 }; // (S088)
Guide_TM( 74 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x59, 0 }; // (S089)
Guide_TM( 75 ) = { 1, TriggerType_Switch1, ScheduleType_Gen, 0x5A, 0 }; // (S090)


// -- Trigger Macro List

// Indexed Table of Trigger Macros
const TriggerMacro TriggerMacroList[] = {
	/* 0 */ Define_TM( 0, 100 ), // (S003) : (layerLock(2) + LCDLayerDisplay());
	/* 1 */ Define_TM( 0, 63 ), // (S003) : (HID(USBCode,default)"69"F12);
	/* 2 */ Define_TM( 1, 31 ), // (S004) : (HID(USBCode,default)"35"6);
	/* 3 */ Define_TM( 1, 57 ), // (S004) : (HID(USBCode,default)"63"F6);
	/* 4 */ Define_TM( 2, 32 ), // (S005) : (HID(USBCode,default)"36"7);
	/* 5 */ Define_TM( 2, 58 ), // (S005) : (HID(USBCode,default)"64"F7);
	/* 6 */ Define_TM( 2, 73 ), // (S005) : (HID(USBCode,default)"83"Num Lock);
	/* 7 */ Define_TM( 3, 33 ), // (S006) : (HID(USBCode,default)"37"8);
	/* 8 */ Define_TM( 3, 59 ), // (S006) : (HID(USBCode,default)"65"F8);
	/* 9 */ Define_TM( 3, 74 ), // (S006) : (HID(USBCode,default)"84"Keypad Slash);
	/* 10 */ Define_TM( 4, 34 ), // (S007) : (HID(USBCode,default)"38"9);
	/* 11 */ Define_TM( 4, 60 ), // (S007) : (HID(USBCode,default)"66"F9);
	/* 12 */ Define_TM( 4, 75 ), // (S007) : (HID(USBCode,default)"85"Keypad Asterisk);
	/* 13 */ Define_TM( 5, 35 ), // (S008) : (HID(USBCode,default)"39"0);
	/* 14 */ Define_TM( 5, 61 ), // (S008) : (HID(USBCode,default)"67"F10);
	/* 15 */ Define_TM( 5, 76 ), // (S008) : (HID(USBCode,default)"86"Keypad Minus);
	/* 16 */ Define_TM( 6, 41 ), // (S009) : (HID(USBCode,default)"45"Minus);
	/* 17 */ Define_TM( 7, 43 ), // (S012) : (HID(USBCode,default)"47"Left Bracket);
	/* 18 */ Define_TM( 8, 24 ), // (S013) : (HID(USBCode,default)"28"Y);
	/* 19 */ Define_TM( 9, 20 ), // (S014) : (HID(USBCode,default)"24"U);
	/* 20 */ Define_TM( 9, 85 ), // (S014) : (HID(USBCode,default)"95"Keypad 7);
	/* 21 */ Define_TM( 10, 8 ), // (S015) : (HID(USBCode,default)"12"I);
	/* 22 */ Define_TM( 10, 86 ), // (S015) : (HID(USBCode,default)"96"Keypad 8);
	/* 23 */ Define_TM( 11, 14 ), // (S016) : (HID(USBCode,default)"18"O);
	/* 24 */ Define_TM( 11, 87 ), // (S016) : (HID(USBCode,default)"97"Keypad 9);
	/* 25 */ Define_TM( 12, 15 ), // (S017) : (HID(USBCode,default)"19"P);
	/* 26 */ Define_TM( 12, 77 ), // (S017) : (HID(USBCode,default)"87"Keypad Plus);
	/* 27 */ Define_TM( 13, 44 ), // (S018) : (HID(USBCode,default)"48"Right Bracket);
	/* 28 */ Define_TM( 14, 7 ), // (S022) : (HID(USBCode,default)"11"H);
	/* 29 */ Define_TM( 15, 9 ), // (S023) : (HID(USBCode,default)"13"J);
	/* 30 */ Define_TM( 15, 82 ), // (S023) : (HID(USBCode,default)"92"Keypad 4);
	/* 31 */ Define_TM( 16, 10 ), // (S024) : (HID(USBCode,default)"14"K);
	/* 32 */ Define_TM( 16, 83 ), // (S024) : (HID(USBCode,default)"93"Keypad 5);
	/* 33 */ Define_TM( 17, 11 ), // (S025) : (HID(USBCode,default)"15"L);
	/* 34 */ Define_TM( 17, 84 ), // (S025) : (HID(USBCode,default)"94"Keypad 6);
	/* 35 */ Define_TM( 18, 46 ), // (S026) : (HID(USBCode,default)"51"Semicolon);
	/* 36 */ Define_TM( 18, 77 ), // (S026) : (HID(USBCode,default)"87"Keypad Plus);
	/* 37 */ Define_TM( 19, 47 ), // (S027) : (HID(USBCode,default)"52"Quote);
	/* 38 */ Define_TM( 20, 96 ), // (S028) : (HID(USBCode,default)"230"Right Alt);
	/* 39 */ Define_TM( 21, 94 ), // (S029) : (HID(USBCode,default)"228"Right Control);
	/* 40 */ Define_TM( 22, 101 ), // (S030) : (layerShift(1) + LCDLayerDisplay());
	/* 41 */ Define_TM( 23, 13 ), // (S031) : (HID(USBCode,default)"17"N);
	/* 42 */ Define_TM( 24, 12 ), // (S032) : (HID(USBCode,default)"16"M);
	/* 43 */ Define_TM( 24, 79 ), // (S032) : (HID(USBCode,default)"89"Keypad 1);
	/* 44 */ Define_TM( 25, 49 ), // (S033) : (HID(USBCode,default)"54"Comma);
	/* 45 */ Define_TM( 25, 80 ), // (S033) : (HID(USBCode,default)"90"Keypad 2);
	/* 46 */ Define_TM( 26, 50 ), // (S034) : (HID(USBCode,default)"55"Period);
	/* 47 */ Define_TM( 26, 81 ), // (S034) : (HID(USBCode,default)"91"Keypad 3);
	/* 48 */ Define_TM( 27, 51 ), // (S035) : (HID(USBCode,default)"56"Slash);
	/* 49 */ Define_TM( 27, 78 ), // (S035) : (HID(USBCode,default)"88"Keypad Enter);
	/* 50 */ Define_TM( 28, 95 ), // (S036) : (HID(USBCode,default)"229"Right Shift);
	/* 51 */ Define_TM( 29, 65 ), // (S037) : (HID(USBCode,default)"75"Page Up);
	/* 52 */ Define_TM( 30, 68 ), // (S038) : (HID(USBCode,default)"78"Page Down);
	/* 53 */ Define_TM( 31, 36 ), // (S039) : (HID(USBCode,default)"40"Enter);
	/* 54 */ Define_TM( 32, 40 ), // (S040) : (HID(USBCode,default)"44"Space);
	/* 55 */ Define_TM( 32, 88 ), // (S040) : (HID(USBCode,default)"98"Keypad 0);
	/* 56 */ Define_TM( 33, 70 ), // (S041) : (HID(USBCode,default)"80"Left);
	/* 57 */ Define_TM( 34, 71 ), // (S042) : (HID(USBCode,default)"81"Down);
	/* 58 */ Define_TM( 35, 72 ), // (S043) : (HID(USBCode,default)"82"Up);
	/* 59 */ Define_TM( 35, 89 ), // (S043) : (HID(USBCode,default)"99"Keypad Period);
	/* 60 */ Define_TM( 36, 69 ), // (S044) : (HID(USBCode,default)"79"Right);
	/* 61 */ Define_TM( 36, 78 ), // (S044) : (HID(USBCode,default)"88"Keypad Enter);
	/* 62 */ Define_TM( 37, 97 ), // (S045) : (HID(USBCode,default)"231"Right GUI);
	/* 63 */ Define_TM( 38, 37 ), // (S048) : (HID(USBCode,default)"41"Esc);
	/* 64 */ Define_TM( 38, 62 ), // (S048) : (HID(USBCode,default)"68"F11);
	/* 65 */ Define_TM( 39, 30 ), // (S049) : (HID(USBCode,default)"34"5);
	/* 66 */ Define_TM( 39, 56 ), // (S049) : (HID(USBCode,default)"62"F5);
	/* 67 */ Define_TM( 40, 29 ), // (S050) : (HID(USBCode,default)"33"4);
	/* 68 */ Define_TM( 40, 55 ), // (S050) : (HID(USBCode,default)"61"F4);
	/* 69 */ Define_TM( 41, 28 ), // (S051) : (HID(USBCode,default)"32"3);
	/* 70 */ Define_TM( 41, 54 ), // (S051) : (HID(USBCode,default)"60"F3);
	/* 71 */ Define_TM( 42, 27 ), // (S052) : (HID(USBCode,default)"31"2);
	/* 72 */ Define_TM( 42, 53 ), // (S052) : (HID(USBCode,default)"59"F2);
	/* 73 */ Define_TM( 43, 26 ), // (S053) : (HID(USBCode,default)"30"1);
	/* 74 */ Define_TM( 43, 52 ), // (S053) : (HID(USBCode,default)"58"F1);
	/* 75 */ Define_TM( 44, 42 ), // (S054) : (HID(USBCode,default)"46"Equal);
	/* 76 */ Define_TM( 44, 98 ), // (S054) : (flashMode());
	/* 77 */ Define_TM( 45, 99 ), // (S057) : (layerLock(1) + LCDLayerDisplay());
	/* 78 */ Define_TM( 46, 19 ), // (S058) : (HID(USBCode,default)"23"T);
	/* 79 */ Define_TM( 47, 17 ), // (S059) : (HID(USBCode,default)"21"R);
	/* 80 */ Define_TM( 48, 4 ), // (S060) : (HID(USBCode,default)"8"E);
	/* 81 */ Define_TM( 49, 22 ), // (S061) : (HID(USBCode,default)"26"W);
	/* 82 */ Define_TM( 50, 16 ), // (S062) : (HID(USBCode,default)"20"Q);
	/* 83 */ Define_TM( 51, 45 ), // (S063) : (HID(USBCode,default)"49"Backslash);
	/* 84 */ Define_TM( 52, 6 ), // (S067) : (HID(USBCode,default)"10"G);
	/* 85 */ Define_TM( 53, 5 ), // (S068) : (HID(USBCode,default)"9"F);
	/* 86 */ Define_TM( 54, 3 ), // (S069) : (HID(USBCode,default)"7"D);
	/* 87 */ Define_TM( 55, 18 ), // (S070) : (HID(USBCode,default)"22"S);
	/* 88 */ Define_TM( 56, 0 ), // (S071) : (HID(USBCode,default)"4"A);
	/* 89 */ Define_TM( 57, 39 ), // (S072) : (HID(USBCode,default)"43"Tab);
	/* 90 */ Define_TM( 58, 92 ), // (S073) : (HID(USBCode,default)"226"Left Alt);
	/* 91 */ Define_TM( 59, 90 ), // (S074) : (HID(USBCode,default)"224"Left Control);
	/* 92 */ Define_TM( 60, 101 ), // (S075) : (layerShift(1) + LCDLayerDisplay());
	/* 93 */ Define_TM( 61, 1 ), // (S076) : (HID(USBCode,default)"5"B);
	/* 94 */ Define_TM( 62, 21 ), // (S077) : (HID(USBCode,default)"25"V);
	/* 95 */ Define_TM( 63, 2 ), // (S078) : (HID(USBCode,default)"6"C);
	/* 96 */ Define_TM( 64, 23 ), // (S079) : (HID(USBCode,default)"27"X);
	/* 97 */ Define_TM( 65, 25 ), // (S080) : (HID(USBCode,default)"29"Z);
	/* 98 */ Define_TM( 66, 91 ), // (S081) : (HID(USBCode,default)"225"Left Shift);
	/* 99 */ Define_TM( 67, 64 ), // (S082) : (HID(USBCode,default)"74"Home);
	/* 100 */ Define_TM( 68, 67 ), // (S083) : (HID(USBCode,default)"77"End);
	/* 101 */ Define_TM( 69, 66 ), // (S084) : (HID(USBCode,default)"76"Delete);
	/* 102 */ Define_TM( 70, 38 ), // (S085) : (HID(USBCode,default)"42"Backspace);
	/* 103 */ Define_TM( 71, 69 ), // (S086) : (HID(USBCode,default)"79"Right);
	/* 104 */ Define_TM( 72, 70 ), // (S087) : (HID(USBCode,default)"80"Left);
	/* 105 */ Define_TM( 73, 45 ), // (S088) : (HID(USBCode,default)"49"Backslash);
	/* 106 */ Define_TM( 74, 48 ), // (S089) : (HID(USBCode,default)"53"Backtick);
	/* 107 */ Define_TM( 75, 93 ), // (S090) : (HID(USBCode,default)"227"Left GUI);
};


// -- Trigger Macro Record List

// Keeps a record/state of each trigger macro
TriggerMacroRecord TriggerMacroRecordList[ TriggerMacroNum ];



// ----- Trigger Maps -----

// MaxScanCode
// - This is retrieved from the KLL configuration
// - Should be corollated with the max scan code in the scan module
// - Maximum value is 0x100 (0x0 to 0xFF)
// - Increasing it beyond the keyboard's capabilities is just a waste of ram...
#define MaxScanCode 0x5A

// -- Trigger Lists
//
// Index 0: # of triggers in list
// Index n: pointer to trigger macro - use tm() macro

// - Default Layer -
Define_TL( default, 0x00 ) = { 0 };
Define_TL( default, 0x01 ) = { 0 };
Define_TL( default, 0x02 ) = { 0 };
Define_TL( default, 0x03 ) = { 1, 0 };
Define_TL( default, 0x04 ) = { 1, 2 };
Define_TL( default, 0x05 ) = { 1, 4 };
Define_TL( default, 0x06 ) = { 1, 7 };
Define_TL( default, 0x07 ) = { 1, 10 };
Define_TL( default, 0x08 ) = { 1, 13 };
Define_TL( default, 0x09 ) = { 1, 16 };
Define_TL( default, 0x0A ) = { 0 };
Define_TL( default, 0x0B ) = { 0 };
Define_TL( default, 0x0C ) = { 1, 17 };
Define_TL( default, 0x0D ) = { 1, 18 };
Define_TL( default, 0x0E ) = { 1, 19 };
Define_TL( default, 0x0F ) = { 1, 21 };
Define_TL( default, 0x10 ) = { 1, 23 };
Define_TL( default, 0x11 ) = { 1, 25 };
Define_TL( default, 0x12 ) = { 1, 27 };
Define_TL( default, 0x13 ) = { 0 };
Define_TL( default, 0x14 ) = { 0 };
Define_TL( default, 0x15 ) = { 0 };
Define_TL( default, 0x16 ) = { 1, 28 };
Define_TL( default, 0x17 ) = { 1, 29 };
Define_TL( default, 0x18 ) = { 1, 31 };
Define_TL( default, 0x19 ) = { 1, 33 };
Define_TL( default, 0x1A ) = { 1, 35 };
Define_TL( default, 0x1B ) = { 1, 37 };
Define_TL( default, 0x1C ) = { 1, 38 };
Define_TL( default, 0x1D ) = { 1, 39 };
Define_TL( default, 0x1E ) = { 1, 40 };
Define_TL( default, 0x1F ) = { 1, 41 };
Define_TL( default, 0x20 ) = { 1, 42 };
Define_TL( default, 0x21 ) = { 1, 44 };
Define_TL( default, 0x22 ) = { 1, 46 };
Define_TL( default, 0x23 ) = { 1, 48 };
Define_TL( default, 0x24 ) = { 1, 50 };
Define_TL( default, 0x25 ) = { 1, 51 };
Define_TL( default, 0x26 ) = { 1, 52 };
Define_TL( default, 0x27 ) = { 1, 53 };
Define_TL( default, 0x28 ) = { 1, 54 };
Define_TL( default, 0x29 ) = { 1, 56 };
Define_TL( default, 0x2A ) = { 1, 57 };
Define_TL( default, 0x2B ) = { 1, 58 };
Define_TL( default, 0x2C ) = { 1, 60 };
Define_TL( default, 0x2D ) = { 1, 62 };
Define_TL( default, 0x2E ) = { 0 };
Define_TL( default, 0x2F ) = { 0 };
Define_TL( default, 0x30 ) = { 1, 63 };
Define_TL( default, 0x31 ) = { 1, 65 };
Define_TL( default, 0x32 ) = { 1, 67 };
Define_TL( default, 0x33 ) = { 1, 69 };
Define_TL( default, 0x34 ) = { 1, 71 };
Define_TL( default, 0x35 ) = { 1, 73 };
Define_TL( default, 0x36 ) = { 1, 75 };
Define_TL( default, 0x37 ) = { 0 };
Define_TL( default, 0x38 ) = { 0 };
Define_TL( default, 0x39 ) = { 1, 77 };
Define_TL( default, 0x3A ) = { 1, 78 };
Define_TL( default, 0x3B ) = { 1, 79 };
Define_TL( default, 0x3C ) = { 1, 80 };
Define_TL( default, 0x3D ) = { 1, 81 };
Define_TL( default, 0x3E ) = { 1, 82 };
Define_TL( default, 0x3F ) = { 1, 83 };
Define_TL( default, 0x40 ) = { 0 };
Define_TL( default, 0x41 ) = { 0 };
Define_TL( default, 0x42 ) = { 0 };
Define_TL( default, 0x43 ) = { 1, 84 };
Define_TL( default, 0x44 ) = { 1, 85 };
Define_TL( default, 0x45 ) = { 1, 86 };
Define_TL( default, 0x46 ) = { 1, 87 };
Define_TL( default, 0x47 ) = { 1, 88 };
Define_TL( default, 0x48 ) = { 1, 89 };
Define_TL( default, 0x49 ) = { 1, 90 };
Define_TL( default, 0x4A ) = { 1, 91 };
Define_TL( default, 0x4B ) = { 1, 92 };
Define_TL( default, 0x4C ) = { 1, 93 };
Define_TL( default, 0x4D ) = { 1, 94 };
Define_TL( default, 0x4E ) = { 1, 95 };
Define_TL( default, 0x4F ) = { 1, 96 };
Define_TL( default, 0x50 ) = { 1, 97 };
Define_TL( default, 0x51 ) = { 1, 98 };
Define_TL( default, 0x52 ) = { 1, 99 };
Define_TL( default, 0x53 ) = { 1, 100 };
Define_TL( default, 0x54 ) = { 1, 101 };
Define_TL( default, 0x55 ) = { 1, 102 };
Define_TL( default, 0x56 ) = { 1, 103 };
Define_TL( default, 0x57 ) = { 1, 104 };
Define_TL( default, 0x58 ) = { 1, 105 };
Define_TL( default, 0x59 ) = { 1, 106 };
Define_TL( default, 0x5A ) = { 1, 107 };


// - Partial Layers -
// Partial Layer 1
Define_TL( layer1, 0x00 ) = { 1, 1 };
Define_TL( layer1, 0x01 ) = { 1, 3 };
Define_TL( layer1, 0x02 ) = { 1, 5 };
Define_TL( layer1, 0x03 ) = { 1, 8 };
Define_TL( layer1, 0x04 ) = { 1, 11 };
Define_TL( layer1, 0x05 ) = { 1, 14 };
Define_TL( layer1, 0x06 ) = { 0 };
Define_TL( layer1, 0x07 ) = { 0 };
Define_TL( layer1, 0x08 ) = { 0 };
Define_TL( layer1, 0x09 ) = { 0 };
Define_TL( layer1, 0x0A ) = { 0 };
Define_TL( layer1, 0x0B ) = { 0 };
Define_TL( layer1, 0x0C ) = { 0 };
Define_TL( layer1, 0x0D ) = { 0 };
Define_TL( layer1, 0x0E ) = { 0 };
Define_TL( layer1, 0x0F ) = { 0 };
Define_TL( layer1, 0x10 ) = { 0 };
Define_TL( layer1, 0x11 ) = { 0 };
Define_TL( layer1, 0x12 ) = { 0 };
Define_TL( layer1, 0x13 ) = { 0 };
Define_TL( layer1, 0x14 ) = { 0 };
Define_TL( layer1, 0x15 ) = { 0 };
Define_TL( layer1, 0x16 ) = { 0 };
Define_TL( layer1, 0x17 ) = { 0 };
Define_TL( layer1, 0x18 ) = { 0 };
Define_TL( layer1, 0x19 ) = { 0 };
Define_TL( layer1, 0x1A ) = { 0 };
Define_TL( layer1, 0x1B ) = { 0 };
Define_TL( layer1, 0x1C ) = { 0 };
Define_TL( layer1, 0x1D ) = { 0 };
Define_TL( layer1, 0x1E ) = { 0 };
Define_TL( layer1, 0x1F ) = { 0 };
Define_TL( layer1, 0x20 ) = { 0 };
Define_TL( layer1, 0x21 ) = { 0 };
Define_TL( layer1, 0x22 ) = { 0 };
Define_TL( layer1, 0x23 ) = { 0 };
Define_TL( layer1, 0x24 ) = { 0 };
Define_TL( layer1, 0x25 ) = { 0 };
Define_TL( layer1, 0x26 ) = { 0 };
Define_TL( layer1, 0x27 ) = { 0 };
Define_TL( layer1, 0x28 ) = { 0 };
Define_TL( layer1, 0x29 ) = { 0 };
Define_TL( layer1, 0x2A ) = { 0 };
Define_TL( layer1, 0x2B ) = { 0 };
Define_TL( layer1, 0x2C ) = { 0 };
Define_TL( layer1, 0x2D ) = { 1, 64 };
Define_TL( layer1, 0x2E ) = { 1, 66 };
Define_TL( layer1, 0x2F ) = { 1, 68 };
Define_TL( layer1, 0x30 ) = { 1, 70 };
Define_TL( layer1, 0x31 ) = { 1, 72 };
Define_TL( layer1, 0x32 ) = { 1, 74 };

// Partial Layer 2
Define_TL( layer2, 0x00 ) = { 1, 6 };
Define_TL( layer2, 0x01 ) = { 1, 9 };
Define_TL( layer2, 0x02 ) = { 1, 12 };
Define_TL( layer2, 0x03 ) = { 1, 15 };
Define_TL( layer2, 0x04 ) = { 0 };
Define_TL( layer2, 0x05 ) = { 0 };
Define_TL( layer2, 0x06 ) = { 0 };
Define_TL( layer2, 0x07 ) = { 0 };
Define_TL( layer2, 0x08 ) = { 0 };
Define_TL( layer2, 0x09 ) = { 1, 20 };
Define_TL( layer2, 0x0A ) = { 1, 22 };
Define_TL( layer2, 0x0B ) = { 1, 24 };
Define_TL( layer2, 0x0C ) = { 1, 26 };
Define_TL( layer2, 0x0D ) = { 0 };
Define_TL( layer2, 0x0E ) = { 0 };
Define_TL( layer2, 0x0F ) = { 0 };
Define_TL( layer2, 0x10 ) = { 0 };
Define_TL( layer2, 0x11 ) = { 0 };
Define_TL( layer2, 0x12 ) = { 1, 30 };
Define_TL( layer2, 0x13 ) = { 1, 32 };
Define_TL( layer2, 0x14 ) = { 1, 34 };
Define_TL( layer2, 0x15 ) = { 1, 36 };
Define_TL( layer2, 0x16 ) = { 0 };
Define_TL( layer2, 0x17 ) = { 0 };
Define_TL( layer2, 0x18 ) = { 0 };
Define_TL( layer2, 0x19 ) = { 0 };
Define_TL( layer2, 0x1A ) = { 0 };
Define_TL( layer2, 0x1B ) = { 1, 43 };
Define_TL( layer2, 0x1C ) = { 1, 45 };
Define_TL( layer2, 0x1D ) = { 1, 47 };
Define_TL( layer2, 0x1E ) = { 1, 49 };
Define_TL( layer2, 0x1F ) = { 0 };
Define_TL( layer2, 0x20 ) = { 0 };
Define_TL( layer2, 0x21 ) = { 0 };
Define_TL( layer2, 0x22 ) = { 0 };
Define_TL( layer2, 0x23 ) = { 1, 55 };
Define_TL( layer2, 0x24 ) = { 0 };
Define_TL( layer2, 0x25 ) = { 0 };
Define_TL( layer2, 0x26 ) = { 1, 59 };
Define_TL( layer2, 0x27 ) = { 1, 61 };
Define_TL( layer2, 0x28 ) = { 0 };
Define_TL( layer2, 0x29 ) = { 0 };
Define_TL( layer2, 0x2A ) = { 0 };
Define_TL( layer2, 0x2B ) = { 0 };
Define_TL( layer2, 0x2C ) = { 0 };
Define_TL( layer2, 0x2D ) = { 0 };
Define_TL( layer2, 0x2E ) = { 0 };
Define_TL( layer2, 0x2F ) = { 0 };
Define_TL( layer2, 0x30 ) = { 0 };
Define_TL( layer2, 0x31 ) = { 1, 76 };


// -- ScanCode Offset Map
// Maps interconnect ids to scancode offsets
//
// Only used for keyboards with an interconnect
const uint8_t InterconnectOffsetList[] = {
	0x00,
	0x2D,
	0x5A,
};


// -- ScanCode Indexed Maps
// Maps to a trigger list of macro pointers
//                 _
// <scan code> -> |T|
//                |r| -> <trigger macro pointer 1>
//                |i|
//                |g| -> <trigger macro pointer 2>
//                |g|
//                |e| -> <trigger macro pointer 3>
//                |r|
//                |s| -> <trigger macro pointer n>
//                 -

// - Default Map for ScanCode Lookup -
const nat_ptr_t *default_scanMap[] = { 
default_tl_0x00, default_tl_0x01, default_tl_0x02, default_tl_0x03, default_tl_0x04, default_tl_0x05, default_tl_0x06, default_tl_0x07, default_tl_0x08, default_tl_0x09, default_tl_0x0A, default_tl_0x0B, default_tl_0x0C, default_tl_0x0D, default_tl_0x0E, default_tl_0x0F, default_tl_0x10, default_tl_0x11, default_tl_0x12, default_tl_0x13, default_tl_0x14, default_tl_0x15, default_tl_0x16, default_tl_0x17, default_tl_0x18, default_tl_0x19, default_tl_0x1A, default_tl_0x1B, default_tl_0x1C, default_tl_0x1D, default_tl_0x1E, default_tl_0x1F, default_tl_0x20, default_tl_0x21, default_tl_0x22, default_tl_0x23, default_tl_0x24, default_tl_0x25, default_tl_0x26, default_tl_0x27, default_tl_0x28, default_tl_0x29, default_tl_0x2A, default_tl_0x2B, default_tl_0x2C, default_tl_0x2D, default_tl_0x2E, default_tl_0x2F, default_tl_0x30, default_tl_0x31, default_tl_0x32, default_tl_0x33, default_tl_0x34, default_tl_0x35, default_tl_0x36, default_tl_0x37, default_tl_0x38, default_tl_0x39, default_tl_0x3A, default_tl_0x3B, default_tl_0x3C, default_tl_0x3D, default_tl_0x3E, default_tl_0x3F, default_tl_0x40, default_tl_0x41, default_tl_0x42, default_tl_0x43, default_tl_0x44, default_tl_0x45, default_tl_0x46, default_tl_0x47, default_tl_0x48, default_tl_0x49, default_tl_0x4A, default_tl_0x4B, default_tl_0x4C, default_tl_0x4D, default_tl_0x4E, default_tl_0x4F, default_tl_0x50, default_tl_0x51, default_tl_0x52, default_tl_0x53, default_tl_0x54, default_tl_0x55, default_tl_0x56, default_tl_0x57, default_tl_0x58, default_tl_0x59, default_tl_0x5A
};


// - Partial Layer ScanCode Lookup Maps -
// Partial Layer 1
const nat_ptr_t *layer1_scanMap[] = { 
layer1_tl_0x00, layer1_tl_0x01, layer1_tl_0x02, layer1_tl_0x03, layer1_tl_0x04, layer1_tl_0x05, layer1_tl_0x06, layer1_tl_0x07, layer1_tl_0x08, layer1_tl_0x09, layer1_tl_0x0A, layer1_tl_0x0B, layer1_tl_0x0C, layer1_tl_0x0D, layer1_tl_0x0E, layer1_tl_0x0F, layer1_tl_0x10, layer1_tl_0x11, layer1_tl_0x12, layer1_tl_0x13, layer1_tl_0x14, layer1_tl_0x15, layer1_tl_0x16, layer1_tl_0x17, layer1_tl_0x18, layer1_tl_0x19, layer1_tl_0x1A, layer1_tl_0x1B, layer1_tl_0x1C, layer1_tl_0x1D, layer1_tl_0x1E, layer1_tl_0x1F, layer1_tl_0x20, layer1_tl_0x21, layer1_tl_0x22, layer1_tl_0x23, layer1_tl_0x24, layer1_tl_0x25, layer1_tl_0x26, layer1_tl_0x27, layer1_tl_0x28, layer1_tl_0x29, layer1_tl_0x2A, layer1_tl_0x2B, layer1_tl_0x2C, layer1_tl_0x2D, layer1_tl_0x2E, layer1_tl_0x2F, layer1_tl_0x30, layer1_tl_0x31, layer1_tl_0x32
};

// Partial Layer 2
const nat_ptr_t *layer2_scanMap[] = { 
layer2_tl_0x00, layer2_tl_0x01, layer2_tl_0x02, layer2_tl_0x03, layer2_tl_0x04, layer2_tl_0x05, layer2_tl_0x06, layer2_tl_0x07, layer2_tl_0x08, layer2_tl_0x09, layer2_tl_0x0A, layer2_tl_0x0B, layer2_tl_0x0C, layer2_tl_0x0D, layer2_tl_0x0E, layer2_tl_0x0F, layer2_tl_0x10, layer2_tl_0x11, layer2_tl_0x12, layer2_tl_0x13, layer2_tl_0x14, layer2_tl_0x15, layer2_tl_0x16, layer2_tl_0x17, layer2_tl_0x18, layer2_tl_0x19, layer2_tl_0x1A, layer2_tl_0x1B, layer2_tl_0x1C, layer2_tl_0x1D, layer2_tl_0x1E, layer2_tl_0x1F, layer2_tl_0x20, layer2_tl_0x21, layer2_tl_0x22, layer2_tl_0x23, layer2_tl_0x24, layer2_tl_0x25, layer2_tl_0x26, layer2_tl_0x27, layer2_tl_0x28, layer2_tl_0x29, layer2_tl_0x2A, layer2_tl_0x2B, layer2_tl_0x2C, layer2_tl_0x2D, layer2_tl_0x2E, layer2_tl_0x2F, layer2_tl_0x30, layer2_tl_0x31
};



// ----- Layer Index -----

// -- Layer Index List
//
// Index 0: Default map
// Index n: Additional layers
const Layer LayerIndex[] = {
	Layer_IN( default_scanMap, "D: dev_keyboard_utilities_ergodox_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_STLcd@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_UARTConnect@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Macro_PartialMap@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Macro_PixelMap@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Output_HID-IO@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Output_USB@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Debug_latency@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Debug_led@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['scancode_map']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['rightHand']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['slave1']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['leftHand']_processed.kll + .local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['all-leds']_processed.kll + .local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['mdergo1Overlay']_processed.kll + .local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll", 0x00 ),
	Layer_IN( layer1_scanMap, "1: dev_keyboard_utilities_ergodox_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_STLcd@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_UARTConnect@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Macro_PartialMap@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Macro_PixelMap@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Output_HID-IO@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Output_USB@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Debug_latency@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Debug_led@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['scancode_map']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['rightHand']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['slave1']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['leftHand']_processed.kll + .local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['iced_func']_processed.kll", 0x03 ),
	Layer_IN( layer2_scanMap, "2: dev_keyboard_utilities_ergodox_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_STLcd@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Devices_UARTConnect@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Macro_PartialMap@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Macro_PixelMap@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Output_HID-IO@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Output_USB@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Debug_latency@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Debug_led@['capabilities']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['scancode_map']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['rightHand']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['slave1']_processed.kll + dev_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['leftHand']_processed.kll + .local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['iced_numpad']_processed.kll", 0x05 ),
};


// - Layer State
LayerStateType LayerState[ LayerNum ];



// ----- Rotation Parameters -----

// Each position represents the maximum rotation value for the index
const uint8_t Rotation_MaxParameter[] = {
};



// ----- Key Positions -----

// -- Physical Key Positions
//
// Index 0: Key 1
// Each key has 6 dimensions
// x,y,z and rx,ry,rz (rotation)
// Units are in mm
const Position Key_Positions[] = {
	PositionEntry( 118.65, 1.0, 0.0, 0.0, 0.0, 0.0 ), // S003 <= x:118.65,y:1;
	PositionEntry( 99.6, 1.0, 0.0, 0.0, 0.0, 0.0 ), // S004 <= x:99.6,y:1;
	PositionEntry( 80.55, 2.0, 0.0, 0.0, 0.0, 0.0 ), // S005 <= x:80.55,y:2;
	PositionEntry( 61.5, 4.0, 0.0, 0.0, 0.0, 0.0 ), // S006 <= x:61.5,y:4;
	PositionEntry( 42.45, 3.0, 0.0, 0.0, 0.0, 0.0 ), // S007 <= x:42.45,y:3;
	PositionEntry( 23.4, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S008 <= x:23.4,y:0;
	PositionEntry( 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S009 <= x:0,y:0;
	PositionEntry( 118.65, -23.05, 0.0, 0.0, 0.0, 0.0 ), // S012 <= x:118.65,y:-23.05;
	PositionEntry( 99.6, -18.05, 0.0, 0.0, 0.0, 0.0 ), // S013 <= x:99.6,y:-18.05;
	PositionEntry( 80.55, -17.05, 0.0, 0.0, 0.0, 0.0 ), // S014 <= x:80.55,y:-17.05;
	PositionEntry( 61.5, -15.05, 0.0, 0.0, 0.0, 0.0 ), // S015 <= x:61.5,y:-15.05;
	PositionEntry( 42.45, -16.05, 0.0, 0.0, 0.0, 0.0 ), // S016 <= x:42.45,y:-16.05;
	PositionEntry( 23.4, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S017 <= x:23.4,y:-19.05;
	PositionEntry( 0.0, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S018 <= x:0,y:-19.05;
	PositionEntry( 99.6, -37.1, 0.0, 0.0, 0.0, 0.0 ), // S022 <= x:99.6,y:-37.1;
	PositionEntry( 80.55, -36.1, 0.0, 0.0, 0.0, 0.0 ), // S023 <= x:80.55,y:-36.1;
	PositionEntry( 61.5, -34.1, 0.0, 0.0, 0.0, 0.0 ), // S024 <= x:61.5,y:-34.1;
	PositionEntry( 42.45, -35.1, 0.0, 0.0, 0.0, 0.0 ), // S025 <= x:42.45,y:-35.1;
	PositionEntry( 23.4, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S026 <= x:23.4,y:-38.1;
	PositionEntry( 0.0, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S027 <= x:0,y:-38.1;
	PositionEntry( 154.95, -75.05, 0.0, 0.0, 0.0, 0.0 ), // S028 <= x:154.95,y:-75.05;
	PositionEntry( 138.65, -68.05, 0.0, 0.0, 0.0, 0.0 ), // S029 <= x:138.65,y:-68.05;
	PositionEntry( 118.65, -51.05, 0.0, 0.0, 0.0, 0.0 ), // S030 <= x:118.65,y:-51.05;
	PositionEntry( 99.6, -56.15, 0.0, 0.0, 0.0, 0.0 ), // S031 <= x:99.6,y:-56.15;
	PositionEntry( 80.55, -55.15, 0.0, 0.0, 0.0, 0.0 ), // S032 <= x:80.55,y:-55.15;
	PositionEntry( 61.5, -53.15, 0.0, 0.0, 0.0, 0.0 ), // S033 <= x:61.5,y:-53.15;
	PositionEntry( 42.45, -54.15, 0.0, 0.0, 0.0, 0.0 ), // S034 <= x:42.45,y:-54.15;
	PositionEntry( 23.4, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S035 <= x:23.4,y:-57.15;
	PositionEntry( 0.0, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S036 <= x:0,y:-57.15;
	PositionEntry( 147.0, -91.2, 0.0, 0.0, 0.0, 0.0 ), // S037 <= x:147,y:-91.2;
	PositionEntry( 139.8, -109.2, 0.0, 0.0, 0.0, 0.0 ), // S038 <= x:139.8,y:-109.2;
	PositionEntry( 126.4, -93.2, 0.0, 0.0, 0.0, 0.0 ), // S039 <= x:126.4,y:-93.2;
	PositionEntry( 109.1, -86.2, 0.0, 0.0, 0.0, 0.0 ), // S040 <= x:109.1,y:-86.2;
	PositionEntry( 80.55, -74.2, 0.0, 0.0, 0.0, 0.0 ), // S041 <= x:80.55,y:-74.2;
	PositionEntry( 61.5, -72.2, 0.0, 0.0, 0.0, 0.0 ), // S042 <= x:61.5,y:-72.2;
	PositionEntry( 42.45, -73.2, 0.0, 0.0, 0.0, 0.0 ), // S043 <= x:42.45,y:-73.2;
	PositionEntry( 23.4, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S044 <= x:23.4,y:-76.2;
	PositionEntry( 5.0, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S045 <= x:5,y:-76.2;
};

