/* Copyright (C) 2018 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2018-12-03
// KLL Emitter:        kiibohd
// KLL Version:        0.5.6.6
// KLL Git Changes:    None
// Compiler arguments:
//    /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/__main__.py
//    --kiibohd-debug
//    --config
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/ISSILed/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/MatrixARMPeriodic/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/STLcd/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Devices/UARTConnect/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Macro/PartialMap/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Macro/PixelMap/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Output/HID-IO/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Output/USB/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Debug/latency/capabilities.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Debug/led/capabilities.kll
//    --base
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/scancode_map.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/rightHand.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/slave1.kll
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Scan/Infinity_Ergodox/leftHand.kll
//    --default
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/MDErgo1-Default-0.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/infinity_ergodox/lcdFuncMap.kll
//    --partial
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/MDErgo1-Default-1.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/stdFuncMap.kll
//    --partial
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/MDErgo1-Default-2.kll
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/stdFuncMap.kll
//    --emitter
//      kiibohd
//    --def-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/kll_defs.h
//    --map-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/generatedKeymap.h
//    --hid-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/usb_hid.h
//    --pixel-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/generatedPixelmap.c
//    --json-output
//      /Users/tom/.projects_root/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.ICED-R.gcc.make/kll.json
//
// - Configuration File -
//    ISSILedCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_ISSILed@['capabilities']_processed.kll
//    MatrixARMPeriodicCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll
//    STLcdCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_STLcd@['capabilities']_processed.kll
//    UARTConnectCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Devices_UARTConnect@['capabilities']_processed.kll
//    PartialMapCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Macro_PartialMap@['capabilities']_processed.kll
//    PixelMapCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Macro_PixelMap@['capabilities']_processed.kll
//    HID-IOCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Output_HID-IO@['capabilities']_processed.kll
//    USBCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Output_USB@['capabilities']_processed.kll
//    latency
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Debug_latency@['capabilities']_processed.kll
//    led
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Debug_led@['capabilities']_processed.kll
// - Generic Files -
// - Base Layer -
//    Infinity_Ergodox
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['scancode_map']_processed.kll
//    Infinity Ergodox Right Hand
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['rightHand']_processed.kll
//    MDErgo1Slave1
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['slave1']_processed.kll
//    Infinity Ergodox Left Hand
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Scan_Infinity_Ergodox@['leftHand']_processed.kll
// - Default Layer -
//    MDErgo1
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Keyboards_darwin18.0.0.ICED-R.gcc.make@['MDErgo1-Default-0']_processed.kll
//    lcdFuncMap
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll
// - Partial Layers -
//    Layer 1
//     MDErgo1
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Keyboards_darwin18.0.0.ICED-R.gcc.make@['MDErgo1-Default-1']_processed.kll
//     stdFuncMap
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts@['stdFuncMap']_processed.kll
//    Layer 2
//     MDErgo1
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/projects_root_keyboard_utilities_ergodox_controller_Keyboards_darwin18.0.0.ICED-R.gcc.make@['MDErgo1-Default-2']_processed.kll
//     stdFuncMap
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts@['stdFuncMap']_processed.kll


// Refer to https://github.com/hid-io/layouts for specific details
// Generated using https://github.com/hid-io/layouts-python


#pragma once

// ----- Defines -----

// Keyboard + Keypad
#define KEY_NO_EVENT_0 0x00
#define KEY_ERROR_ROLL_OVER_1 0x01
#define KEY_POST_FAIL_2 0x02
#define KEY_ERROR_UNDEFINED_3 0x03
#define KEY_A_4 0x04
#define KEY_B_5 0x05
#define KEY_C_6 0x06
#define KEY_D_7 0x07
#define KEY_E_8 0x08
#define KEY_F_9 0x09
#define KEY_G_10 0x0A
#define KEY_H_11 0x0B
#define KEY_I_12 0x0C
#define KEY_J_13 0x0D
#define KEY_K_14 0x0E
#define KEY_L_15 0x0F
#define KEY_M_16 0x10
#define KEY_N_17 0x11
#define KEY_O_18 0x12
#define KEY_P_19 0x13
#define KEY_Q_20 0x14
#define KEY_R_21 0x15
#define KEY_S_22 0x16
#define KEY_T_23 0x17
#define KEY_U_24 0x18
#define KEY_V_25 0x19
#define KEY_W_26 0x1A
#define KEY_X_27 0x1B
#define KEY_Y_28 0x1C
#define KEY_Z_29 0x1D
#define KEY_1_30 0x1E
#define KEY_2_31 0x1F
#define KEY_3_32 0x20
#define KEY_4_33 0x21
#define KEY_5_34 0x22
#define KEY_6_35 0x23
#define KEY_7_36 0x24
#define KEY_8_37 0x25
#define KEY_9_38 0x26
#define KEY_0_39 0x27
#define KEY_ENTER_40 0x28
#define KEY_ESC_41 0x29
#define KEY_BACKSPACE_42 0x2A
#define KEY_TAB_43 0x2B
#define KEY_SPACE_44 0x2C
#define KEY_MINUS_45 0x2D
#define KEY_EQUAL_46 0x2E
#define KEY_LEFT_BRACKET_47 0x2F
#define KEY_RIGHT_BRACKET_48 0x30
#define KEY_BACKSLASH_49 0x31
#define KEY_NUMBER_50 0x32
#define KEY_SEMICOLON_51 0x33
#define KEY_QUOTE_52 0x34
#define KEY_BACKTICK_53 0x35
#define KEY_COMMA_54 0x36
#define KEY_PERIOD_55 0x37
#define KEY_SLASH_56 0x38
#define KEY_CAPS_LOCK_57 0x39
#define KEY_F1_58 0x3A
#define KEY_F2_59 0x3B
#define KEY_F3_60 0x3C
#define KEY_F4_61 0x3D
#define KEY_F5_62 0x3E
#define KEY_F6_63 0x3F
#define KEY_F7_64 0x40
#define KEY_F8_65 0x41
#define KEY_F9_66 0x42
#define KEY_F10_67 0x43
#define KEY_F11_68 0x44
#define KEY_F12_69 0x45
#define KEY_PRINT_SCREEN_70 0x46
#define KEY_SCROLL_LOCK_71 0x47
#define KEY_PAUSE_72 0x48
#define KEY_INSERT_73 0x49
#define KEY_HOME_74 0x4A
#define KEY_PAGE_UP_75 0x4B
#define KEY_DELETE_76 0x4C
#define KEY_END_77 0x4D
#define KEY_PAGE_DOWN_78 0x4E
#define KEY_RIGHT_79 0x4F
#define KEY_LEFT_80 0x50
#define KEY_DOWN_81 0x51
#define KEY_UP_82 0x52
#define KEY_NUM_LOCK_83 0x53
#define KEY_KEYPAD_SLASH_84 0x54
#define KEY_KEYPAD_ASTERISK_85 0x55
#define KEY_KEYPAD_MINUS_86 0x56
#define KEY_KEYPAD_PLUS_87 0x57
#define KEY_KEYPAD_ENTER_88 0x58
#define KEY_KEYPAD_1_89 0x59
#define KEY_KEYPAD_2_90 0x5A
#define KEY_KEYPAD_3_91 0x5B
#define KEY_KEYPAD_4_92 0x5C
#define KEY_KEYPAD_5_93 0x5D
#define KEY_KEYPAD_6_94 0x5E
#define KEY_KEYPAD_7_95 0x5F
#define KEY_KEYPAD_8_96 0x60
#define KEY_KEYPAD_9_97 0x61
#define KEY_KEYPAD_0_98 0x62
#define KEY_KEYPAD_PERIOD_99 0x63
#define KEY_ISO_SLASH_100 0x64
#define KEY_APP_101 0x65
#define KEY_KEYBOARD_STATUS_102 0x66
#define KEY_KEYPAD_EQUAL_103 0x67
#define KEY_F13_104 0x68
#define KEY_F14_105 0x69
#define KEY_F15_106 0x6A
#define KEY_F16_107 0x6B
#define KEY_F17_108 0x6C
#define KEY_F18_109 0x6D
#define KEY_F19_110 0x6E
#define KEY_F20_111 0x6F
#define KEY_F21_112 0x70
#define KEY_F22_113 0x71
#define KEY_F23_114 0x72
#define KEY_F24_115 0x73
#define KEY_EXEC_116 0x74
#define KEY_HELP_117 0x75
#define KEY_MENU_118 0x76
#define KEY_SELECT_119 0x77
#define KEY_STOP_120 0x78
#define KEY_AGAIN_121 0x79
#define KEY_UNDO_122 0x7A
#define KEY_CUT_123 0x7B
#define KEY_COPY_124 0x7C
#define KEY_PASTE_125 0x7D
#define KEY_FIND_126 0x7E
#define KEY_MUTE_127 0x7F
#define KEY_VOLUME_UP_128 0x80
#define KEY_VOLUME_DOWN_129 0x81
#define KEY_LOCKING_CAPS_LOCK_130 0x82
#define KEY_LOCKING_NUM_LOCK_131 0x83
#define KEY_LOCKING_SCROLL_LOCK_132 0x84
#define KEY_KEYPAD_COMMA_133 0x85
#define KEY_KEYPAD_EQUAL_AS400_134 0x86
#define KEY_INTERNATIONAL1_135 0x87
#define KEY_INTERNATIONAL2_136 0x88
#define KEY_INTERNATIONAL3_137 0x89
#define KEY_INTERNATIONAL4_138 0x8A
#define KEY_INTERNATIONAL5_139 0x8B
#define KEY_INTERNATIONAL6_140 0x8C
#define KEY_INTERNATIONAL7_141 0x8D
#define KEY_INTERNATIONAL8_142 0x8E
#define KEY_INTERNATIONAL9_143 0x8F
#define KEY_LANG1_144 0x90
#define KEY_LANG2_145 0x91
#define KEY_LANG3_146 0x92
#define KEY_LANG4_147 0x93
#define KEY_LANG5_148 0x94
#define KEY_LANG6_149 0x95
#define KEY_LANG7_150 0x96
#define KEY_LANG8_151 0x97
#define KEY_LANG9_152 0x98
#define KEY_ALTERNATE_ERASE_153 0x99
#define KEY_SYSREQ_154 0x9A
#define KEY_CANCEL_155 0x9B
#define KEY_CLEAR_156 0x9C
#define KEY_PRIOR_157 0x9D
#define KEY_RETURN_158 0x9E
#define KEY_SEPARATOR_159 0x9F
#define KEY_OUT_160 0xA0
#define KEY_OPER_161 0xA1
#define KEY_CLEAR_AGAIN_162 0xA2
#define KEY_CRSEL_PROPS_163 0xA3
#define KEY_EXSEL_164 0xA4
#define KEY_KEYPAD_00_176 0xB0
#define KEY_KEYPAD_000_177 0xB1
#define KEY_1000_SEPARATOR_178 0xB2
#define KEY_DECIMAL_SEPARATOR_179 0xB3
#define KEY_CURRENCY_UNIT_180 0xB4
#define KEY_CURRENCY_SUBUNIT_181 0xB5
#define KEY_KEYPAD_LEFT_PARENTHESIS_182 0xB6
#define KEY_KEYPAD_RIGHT_PARENTHESIS_183 0xB7
#define KEY_KEYPAD_LEFT_BRACE_184 0xB8
#define KEY_KEYPAD_RIGHT_BRACE_185 0xB9
#define KEY_KEYPAD_TAB_186 0xBA
#define KEY_KEYPAD_BACKSPACE_187 0xBB
#define KEY_KEYPAD_A_188 0xBC
#define KEY_KEYPAD_B_189 0xBD
#define KEY_KEYPAD_C_190 0xBE
#define KEY_KEYPAD_D_191 0xBF
#define KEY_KEYPAD_E_192 0xC0
#define KEY_KEYPAD_F_193 0xC1
#define KEY_KEYPAD_XOR_194 0xC2
#define KEY_KEYPAD_CHEVRON_195 0xC3
#define KEY_KEYPAD_PERCENT_196 0xC4
#define KEY_KEYPAD_LESS_THAN_197 0xC5
#define KEY_KEYPAD_GREATER_THAN_198 0xC6
#define KEY_KEYPAD_BITAND_199 0xC7
#define KEY_KEYPAD_AND_200 0xC8
#define KEY_KEYPAD_BITOR_201 0xC9
#define KEY_KEYPAD_OR_202 0xCA
#define KEY_KEYPAD_COLON_203 0xCB
#define KEY_KEYPAD_HASH_204 0xCC
#define KEY_KEYPAD_SPACE_205 0xCD
#define KEY_KEYPAD_AT_206 0xCE
#define KEY_KEYPAD_EXCLAMATION_207 0xCF
#define KEY_KEYPAD_MEMORY_STORE_208 0xD0
#define KEY_KEYPAD_MEMORY_RECALL_209 0xD1
#define KEY_KEYPAD_MEMORY_CLEAR_210 0xD2
#define KEY_KEYPAD_MEMORY_ADD_211 0xD3
#define KEY_KEYPAD_MEMORY_SUBTRACT_212 0xD4
#define KEY_KEYPAD_MEMORY_MULTIPLY_213 0xD5
#define KEY_KEYPAD_MEMORY_DIVIDE_214 0xD6
#define KEY_KEYPAD_PLUS_MINUS_215 0xD7
#define KEY_KEYPAD_CLEAR_216 0xD8
#define KEY_KEYPAD_CLEAR_ENTRY_217 0xD9
#define KEY_KEYPAD_BINARY_218 0xDA
#define KEY_KEYPAD_OCTAL_219 0xDB
#define KEY_KEYPAD_DECIMAL_220 0xDC
#define KEY_KEYPAD_HEXIDECIMAL_221 0xDD
#define KEY_LEFT_CONTROL_224 0xE0
#define KEY_LEFT_SHIFT_225 0xE1
#define KEY_LEFT_ALT_226 0xE2
#define KEY_LEFT_GUI_227 0xE3
#define KEY_RIGHT_CONTROL_228 0xE4
#define KEY_RIGHT_SHIFT_229 0xE5
#define KEY_RIGHT_ALT_230 0xE6
#define KEY_RIGHT_GUI_231 0xE7
#define KEY_FUNCTION1_240 0xF0
#define KEY_FUNCTION2_241 0xF1
#define KEY_FUNCTION3_242 0xF2
#define KEY_FUNCTION4_243 0xF3
#define KEY_FUNCTION5_244 0xF4
#define KEY_FUNCTION6_245 0xF5
#define KEY_FUNCTION7_246 0xF6
#define KEY_FUNCTION8_247 0xF7
#define KEY_FUNCTION9_248 0xF8
#define KEY_FUNCTION10_249 0xF9
#define KEY_FUNCTION11_250 0xFA
#define KEY_FUNCTION12_251 0xFB
#define KEY_FUNCTION13_252 0xFC
#define KEY_FUNCTION14_253 0xFD
#define KEY_FUNCTION15_254 0xFE
#define KEY_FUNCTION16_255 0xFF
#define KEY_LOCK1_256 0x100
#define KEY_LOCK2_257 0x101
#define KEY_LOCK3_258 0x102
#define KEY_LOCK4_259 0x103
#define KEY_LOCK5_260 0x104
#define KEY_LOCK6_261 0x105
#define KEY_LOCK7_262 0x106
#define KEY_LOCK8_263 0x107
#define KEY_LOCK9_264 0x108
#define KEY_LOCK10_265 0x109
#define KEY_LOCK11_266 0x10A
#define KEY_LOCK12_267 0x10B
#define KEY_LOCK13_268 0x10C
#define KEY_LOCK14_269 0x10D
#define KEY_LOCK15_270 0x10E
#define KEY_LOCK16_271 0x10F
#define KEY_LATCH1_272 0x110
#define KEY_LATCH2_273 0x111
#define KEY_LATCH3_274 0x112
#define KEY_LATCH4_275 0x113
#define KEY_LATCH5_276 0x114
#define KEY_LATCH6_277 0x115
#define KEY_LATCH7_278 0x116
#define KEY_LATCH8_279 0x117
#define KEY_LATCH9_280 0x118
#define KEY_LATCH10_281 0x119
#define KEY_LATCH11_282 0x11A
#define KEY_LATCH12_283 0x11B
#define KEY_LATCH13_284 0x11C
#define KEY_LATCH14_285 0x11D
#define KEY_LATCH15_286 0x11E
#define KEY_LATCH16_287 0x11F
#define KEY_NEXT_LAYER_288 0x120
#define KEY_PREVIOUS_LAYER_289 0x121



// LED Indicators
#define LED_UNDEFINED_0 0x00
#define LED_NUM_LOCK_1 0x01
#define LED_CAPS_LOCK_2 0x02
#define LED_SCROLL_LOCK_3 0x03
#define LED_COMPOSE_4 0x04
#define LED_KANA_5 0x05
#define LED_POWER_6 0x06
#define LED_SHIFT_7 0x07
#define LED_DO_NOT_DISTURB_8 0x08
#define LED_MUTE_9 0x09
#define LED_TONE_ENABLE_10 0x0A
#define LED_HIGH_CUT_FILTER_11 0x0B
#define LED_LOW_CUT_FILTER_12 0x0C
#define LED_EQUALIZER_ENABLE_13 0x0D
#define LED_SOUND_FIELD_ON_14 0x0E
#define LED_SURROUND_ON_15 0x0F
#define LED_REPEAT_16 0x10
#define LED_STEREO_17 0x11
#define LED_SAMPLE_RATE_DETECT_18 0x12
#define LED_SPINNING_19 0x13
#define LED_CAC_20 0x14
#define LED_CLV_21 0x15
#define LED_RECORDING_FORMAT_DETECT_22 0x16
#define LED_OFF_HOOK_23 0x17
#define LED_RING_24 0x18
#define LED_MESSAGE_WAITING_25 0x19
#define LED_DATA_MODE_26 0x1A
#define LED_BATTERY_OPERATION_27 0x1B
#define LED_BATTERY_OK_28 0x1C
#define LED_BATTERY_LOW_29 0x1D
#define LED_SPEAKER_30 0x1E
#define LED_HEAD_SET_31 0x1F
#define LED_HOLD_32 0x20
#define LED_MICROPHONE_33 0x21
#define LED_COVERAGE_34 0x22
#define LED_NIGHT_MODE_35 0x23
#define LED_SEND_CALLS_36 0x24
#define LED_CALL_PICKUP_37 0x25
#define LED_CONFERENCE_38 0x26
#define LED_STAND_BY_39 0x27
#define LED_CAMERA_ON_40 0x28
#define LED_CAMERA_OFF_41 0x29
#define LED_ON_LINE_42 0x2A
#define LED_OFF_LINE_43 0x2B
#define LED_BUSY_44 0x2C
#define LED_READY_45 0x2D
#define LED_PAPER_OUT_46 0x2E
#define LED_PAPER_JAM_47 0x2F
#define LED_REMOTE_48 0x30
#define LED_FORWARD_49 0x31
#define LED_REVERSE_50 0x32
#define LED_STOP_51 0x33
#define LED_REWIND_52 0x34
#define LED_FAST_FORWARD_53 0x35
#define LED_PLAY_54 0x36
#define LED_PAUSE_55 0x37
#define LED_RECORD_56 0x38
#define LED_ERROR_57 0x39
#define LED_GENERIC_IND_75 0x4B
#define LED_SYS_SUSPEND_76 0x4C
#define LED_EXT_PWR_CONN_77 0x4D



// Mouse Buttons - USB HID 1.12v2 pg 67
// XXX (HaaTa): Not currently generated by hid-io/layouts
#define MOUSE_NOPRESS      0x00
#define MOUSE_PRIMARY      0x01 // Button 1
#define MOUSE_SECONDARY    0x02 // Button 2
#define MOUSE_TERTIARY     0x03 // Button 3
#define MOUSE_BUTTON(x)       x
// Continues to 0xFFFF, the higher the Mouse code, the selector significance descreases
// Buttons can be defined as:
//  Sel - Selector
//  OOC - On/Off Control
//  MC  - Momentary Control
//  OSC - One-Shot Control
// depending on context.


// System Control
#define SYS_POWER_DOWN_129 0x81
#define SYS_SLEEP_130 0x82
#define SYS_WAKE_UP_131 0x83
#define SYS_CONTEXT_MENU_132 0x84
#define SYS_MAIN_MENU_133 0x85
#define SYS_APP_MENU_134 0x86
#define SYS_MENU_HELP_135 0x87
#define SYS_MENU_EXIT_136 0x88
#define SYS_MENU_SELECT_137 0x89
#define SYS_MENU_RIGHT_138 0x8A
#define SYS_MENU_LEFT_139 0x8B
#define SYS_MENU_UP_140 0x8C
#define SYS_MENU_DOWN_141 0x8D
#define SYS_COLD_RESTART_142 0x8E
#define SYS_WARM_RESTART_143 0x8F
#define SYS_DPAD_UP_144 0x90
#define SYS_DPAD_DOWN_145 0x91
#define SYS_DPAD_RIGHT_146 0x92
#define SYS_DPAD_LEFT_147 0x93
#define SYS_DOCK_160 0xA0
#define SYS_UNDOCK_161 0xA1
#define SYS_SETUP_162 0xA2
#define SYS_BREAK_163 0xA3
#define SYS_DEBUGGER_BREAK_164 0xA4
#define SYS_APPLICATION_BREAK_165 0xA5
#define SYS_APPLICATION_DEBUGGER_BREAK_166 0xA6
#define SYS_SPEAKER_MUTE_167 0xA7
#define SYS_HIBERNATE_168 0xA8
#define SYS_DISPLAY_INVERT_176 0xB0
#define SYS_DISPLAY_INTERNAL_177 0xB1
#define SYS_DISPLAY_EXTERNAL_178 0xB2
#define SYS_DISPLAY_BOTH_179 0xB3
#define SYS_DISPLAY_DUAL_180 0xB4
#define SYS_DISPLAY_TOGGLE_INTERNAL_EXTERNAL_181 0xB5
#define SYS_DISPLAY_SWAP_PRIMARY_SECONDARY_182 0xB6
#define SYS_DISPLAY_LCD_AUTOSCALE_183 0xB7



// Consumer Control
#define CONS_10_32 0x020
#define CONS_100_33 0x021
#define CONS_AM_PM_34 0x022
#define CONS_POWER_48 0x030
#define CONS_RESET_49 0x031
#define CONS_SLEEP_50 0x032
#define CONS_SLEEP_AFTER_51 0x033
#define CONS_SLEEP_MODE_52 0x034
#define CONS_ILLUMINATION_53 0x035
#define CONS_MENU_64 0x040
#define CONS_MENU_PICK_65 0x041
#define CONS_MENU_UP_66 0x042
#define CONS_MENU_DOWN_67 0x043
#define CONS_MENU_LEFT_68 0x044
#define CONS_MENU_RIGHT_69 0x045
#define CONS_MENU_ESCAPE_70 0x046
#define CONS_MENU_VALUE_INCREASE_71 0x047
#define CONS_MENU_VALUE_DECREASE_72 0x048
#define CONS_DATA_ON_SCREEN_96 0x060
#define CONS_CLOSED_CAPTION_97 0x061
#define CONS_CLOSED_CAPTION_SELECT_98 0x062
#define CONS_VCR_TV_99 0x063
#define CONS_BROADCAST_MODE_100 0x064
#define CONS_SNAPSHOT_101 0x065
#define CONS_STILL_102 0x066
#define CONS_BRIGHTNESS_INCREMENT_111 0x06F
#define CONS_BRIGHTNESS_DECREMENT_112 0x070
#define CONS_BACKLIGHT_TOGGLE_114 0x072
#define CONS_BRIGHTNESS_MIN_115 0x073
#define CONS_BRIGHTNESS_MAX_116 0x074
#define CONS_BRIGHTNESS_AUTO_117 0x075
#define CONS_ASSIGN_SELECTION_129 0x081
#define CONS_MODE_STEP_130 0x082
#define CONS_RECALL_LAST_131 0x083
#define CONS_ENTER_CHANNEL_132 0x084
#define CONS_ORDER_MOVIE_133 0x085
#define CONS_MEDIA_COMPUTER_136 0x088
#define CONS_MEDIA_TV_137 0x089
#define CONS_MEDIA_WWW_138 0x08A
#define CONS_MEDIA_DVD_139 0x08B
#define CONS_MEDIA_TELEPHONE_140 0x08C
#define CONS_MEDIA_PROGRAM_GUIDE_141 0x08D
#define CONS_MEDIA_VIDEO_PHONE_142 0x08E
#define CONS_MEDIA_SELECT_GAMES_143 0x08F
#define CONS_MEDIA_SELECT_MESSAGES_144 0x090
#define CONS_MEDIA_SELECT_CD_145 0x091
#define CONS_MEDIA_SELECT_VCR_146 0x092
#define CONS_MEDIA_SELECT_TUNER_147 0x093
#define CONS_QUIT_148 0x094
#define CONS_HELP_149 0x095
#define CONS_MEDIA_SELECT_TAPE_150 0x096
#define CONS_MEDIA_SELECT_CABLE_151 0x097
#define CONS_MEDIA_SELECT_SATELLITE_152 0x098
#define CONS_MEDIA_SELECT_SECURITY_153 0x099
#define CONS_MEDIA_SELECT_HOME_154 0x09A
#define CONS_MEDIA_SELECT_CALL_155 0x09B
#define CONS_CHANNEL_INCREMENT_156 0x09C
#define CONS_CAHNNEL_DECREMENT_157 0x09D
#define CONS_MEDIA_SELECT_SAP_158 0x09E
#define CONS_VCR_PLUS_160 0x0A0
#define CONS_ONCE_161 0x0A1
#define CONS_DAILY_162 0x0A2
#define CONS_WEEKLY_163 0x0A3
#define CONS_MONTHLY_164 0x0A4
#define CONS_PLAY_176 0x0B0
#define CONS_PAUSE_177 0x0B1
#define CONS_RECORD_178 0x0B2
#define CONS_FAST_FORWARD_179 0x0B3
#define CONS_REWIND_180 0x0B4
#define CONS_SCAN_NEXT_TRACK_181 0x0B5
#define CONS_SCAN_PREVIOUS_TRACK_182 0x0B6
#define CONS_STOP_183 0x0B7
#define CONS_EJECT_184 0x0B8
#define CONS_RANDOM_PLAY_185 0x0B9
#define CONS_REPEAT_188 0x0BC
#define CONS_TRACK_NORMAL_190 0x0BE
#define CONS_FRAME_FORWARD_192 0x0C0
#define CONS_FRAME_BACK_193 0x0C1
#define CONS_MARK_194 0x0C2
#define CONS_CLEAR_MARK_195 0x0C3
#define CONS_REPEAT_FROM_MARK_196 0x0C4
#define CONS_RETURN_TO_MARK_197 0x0C5
#define CONS_SEARCH_MARK_FORWARDS_198 0x0C6
#define CONS_SEARCH_MARK_BACKWARDS_199 0x0C7
#define CONS_COUNTER_RESET_200 0x0C8
#define CONS_SHOW_COUNTER_201 0x0C9
#define CONS_TRACKING_INCREMENT_202 0x0CA
#define CONS_TRACKING_DECREMENT_203 0x0CB
#define CONS_STOP_EJECT_204 0x0CC
#define CONS_PAUSE_PLAY_205 0x0CD
#define CONS_PLAY_SKIP_206 0x0CE
#define CONS_MUTE_226 0x0E2
#define CONS_BASS_BOOST_229 0x0E5
#define CONS_SURROUND_MODE_230 0x0E6
#define CONS_LOUDNESS_231 0x0E7
#define CONS_MPX_232 0x0E8
#define CONS_VOLUME_UP_233 0x0E9
#define CONS_VOLUME_DOWN_234 0x0EA
#define CONS_SPEED_SELECT_240 0x0F0
#define CONS_STANDARD_PLAY_242 0x0F2
#define CONS_LONG_PLAY_243 0x0F3
#define CONS_EXTENDED_PLAY_244 0x0F4
#define CONS_SLOW_245 0x0F5
#define CONS_FAN_ENABLE_256 0x100
#define CONS_LIGHT_ENABLE_258 0x102
#define CONS_CLIMATE_CONTROL_ENABLE_260 0x104
#define CONS_SECURITY_ENABLE_262 0x106
#define CONS_FIRE_ALARM_263 0x107
#define CONS_MOTION_266 0x10A
#define CONS_DURESS_ALARM_267 0x10B
#define CONS_HOLDUP_ALARM_268 0x10C
#define CONS_MEDICAL_ALARM_269 0x10D
#define CONS_BALANCE_RIGHT_336 0x150
#define CONS_BALANCE_LEFT_337 0x151
#define CONS_BASS_INCREMENT_338 0x152
#define CONS_BASS_DECREMENT_339 0x153
#define CONS_TREBLE_INCREMENT_340 0x154
#define CONS_TREBLE_DECREMENT_341 0x155
#define CONS_SUB_CHANNEL_INCREMENT_369 0x171
#define CONS_SUB_CHANNEL_DECREMENT_370 0x172
#define CONS_ALT_AUDIO_INCREMENT_371 0x173
#define CONS_ALT_AUDIO_DECREMENT_372 0x174
#define CONS_LAUNCH_BUTTON_CONFIG_TOOL_385 0x181
#define CONS_PROGRAMMABLE_BUTTON_CONFIG_386 0x182
#define CONS_CONSUMER_CONTROL_CONFIG_387 0x183
#define CONS_WORD_PROCESSOR_388 0x184
#define CONS_TEXT_EDITOR_389 0x185
#define CONS_SPREADSHEET_390 0x186
#define CONS_GRAPHICS_EDITOR_391 0x187
#define CONS_PRESENTATION_APP_392 0x188
#define CONS_DATABASE_APP_393 0x189
#define CONS_EMAIL_READER_394 0x18A
#define CONS_NEWSREADER_395 0x18B
#define CONS_VOICEMAIL_396 0x18C
#define CONS_CONTACTS_ADDRESS_BOOK_397 0x18D
#define CONS_CALENDAR_SCHEDULE_398 0x18E
#define CONS_TASK_PROJECT_MANAGER_399 0x18F
#define CONS_LOG_JOURNAL_TIMECARD_400 0x190
#define CONS_CHECKBOOK_FINANCE_401 0x191
#define CONS_CALCULATOR_402 0x192
#define CONS_AV_CAPTURE_PLAYBACK_403 0x193
#define CONS_LOCAL_MACHINE_BROWSER_404 0x194
#define CONS_LAN_WAN_BROWSER_405 0x195
#define CONS_INTERNET_BROWSER_406 0x196
#define CONS_REMOTE_NETWORKING_ISP_CONNECT_407 0x197
#define CONS_NETWORK_CONFERENCE_408 0x198
#define CONS_NETWORK_CHAT_409 0x199
#define CONS_TELEPHONY_DIALER_410 0x19A
#define CONS_LOGON_411 0x19B
#define CONS_LOGOFF_412 0x19C
#define CONS_LOGON_LOGOFF_413 0x19D
#define CONS_TERMINAL_LOCK_SCREENSAVER_414 0x19E
#define CONS_CONTROL_PANEL_415 0x19F
#define CONS_COMMAND_LINE_PROCESSOR_RUN_416 0x1A0
#define CONS_PROCESS_TASK_MANAGER_417 0x1A1
#define CONS_SELECT_TAST_APPLICATION_418 0x1A2
#define CONS_NEXT_TASK_APPLICATION_419 0x1A3
#define CONS_PREVIOUS_TASK_APPLICATION_420 0x1A4
#define CONS_PREEMPTIVE_HALT_TASK_APPLICATION_421 0x1A5
#define CONS_INTEGRATED_HELP_CENTER_422 0x1A6
#define CONS_DOCUMENTS_423 0x1A7
#define CONS_THESAURUS_424 0x1A8
#define CONS_DICTIONARY_425 0x1A9
#define CONS_DESKTOP_426 0x1AA
#define CONS_SPELL_CHECK_427 0x1AB
#define CONS_GRAMMAR_CHECK_428 0x1AC
#define CONS_WIRELESS_STATUS_429 0x1AD
#define CONS_KEYBOARD_LAYOUT_430 0x1AE
#define CONS_VIRUS_PROTECTION_431 0x1AF
#define CONS_ENCRYPTION_432 0x1B0
#define CONS_SCREEN_SAVER_433 0x1B1
#define CONS_ALARMS_434 0x1B2
#define CONS_CLOCK_435 0x1B3
#define CONS_FILE_BROWSER_436 0x1B4
#define CONS_POWER_STATUS_437 0x1B5
#define CONS_IMAGE_BROWSER_438 0x1B6
#define CONS_AUDIO_BROWSER_439 0x1B7
#define CONS_MOVIE_BROWSER_440 0x1B8
#define CONS_DIGITAL_RIGHTS_MANAGER_441 0x1B9
#define CONS_DIGITAL_WALLET_442 0x1BA
#define CONS_INSTANT_MESSAGING_444 0x1BC
#define CONS_OEM_FEATURES_TIPS_TUTORIAL_445 0x1BD
#define CONS_OEM_HELP_446 0x1BE
#define CONS_ONLINE_COMMUNITY_447 0x1BF
#define CONS_ENTERTAINMENT_CONTENT_448 0x1C0
#define CONS_ONLINE_SHOPPING_449 0x1C1
#define CONS_SMARTCARD_INFO_HELP_450 0x1C2
#define CONS_MARKET_MONITOR_451 0x1C3
#define CONS_CUSTOMIZED_CORP_NEWS_452 0x1C4
#define CONS_ONLINE_ACTIVITY_453 0x1C5
#define CONS_SEARCH_BROWSER_454 0x1C6
#define CONS_AUDIO_PLAYER_455 0x1C7
#define CONS_NEW_513 0x201
#define CONS_OPEN_514 0x202
#define CONS_CLOSE_515 0x203
#define CONS_EXIT_516 0x204
#define CONS_MAXIMIZE_517 0x205
#define CONS_MINIMIZE_518 0x206
#define CONS_SAVE_519 0x207
#define CONS_PRINT_520 0x208
#define CONS_PROPERTIES_521 0x209
#define CONS_UNDO_538 0x21A
#define CONS_COPY_539 0x21B
#define CONS_CUT_540 0x21C
#define CONS_PASTE_541 0x21D
#define CONS_SELECT_ALL_542 0x21E
#define CONS_FIND_543 0x21F
#define CONS_FIND_AND_REPLACE_544 0x220
#define CONS_SEARCH_545 0x221
#define CONS_GO_TO_546 0x222
#define CONS_HOME_547 0x223
#define CONS_BACK_548 0x224
#define CONS_FORWARD_549 0x225
#define CONS_STOP_550 0x226
#define CONS_REFRESH_551 0x227
#define CONS_PREVIOUS_LINK_552 0x228
#define CONS_NEXT_LINK_553 0x229
#define CONS_BOOKMARKS_554 0x22A
#define CONS_HISTORY_555 0x22B
#define CONS_SUBSCRIPTIONS_556 0x22C
#define CONS_ZOOM_IN_557 0x22D
#define CONS_ZOOM_OUT_558 0x22E
#define CONS_ZOOM_559 0x22F
#define CONS_FULL_SCREEN_VIEW_560 0x230
#define CONS_NORMAL_VIEW_561 0x231
#define CONS_VIEW_TOGGLE_562 0x232
#define CONS_SCROLL_UP_563 0x233
#define CONS_SCROLL_DOWN_564 0x234
#define CONS_SCROLL_565 0x235
#define CONS_PAN_LEFT_566 0x236
#define CONS_PAN_RIGHT_567 0x237
#define CONS_PAN_568 0x238
#define CONS_NEW_WINDOW_569 0x239
#define CONS_TILE_HORIZONTALLY_570 0x23A
#define CONS_TILE_VERTICALLY_571 0x23B
#define CONS_FORMAT_572 0x23C
#define CONS_EDIT_573 0x23D
#define CONS_BOLD_574 0x23E
#define CONS_ITALICS_575 0x23F
#define CONS_UNDERLINE_576 0x240
#define CONS_STRIKETHROUGH_577 0x241
#define CONS_SUBSCRIPT_578 0x242
#define CONS_SUPERSCRIPT_579 0x243
#define CONS_ALL_CAPS_580 0x244
#define CONS_ROTATE_581 0x245
#define CONS_RESIZE_582 0x246
#define CONS_FILP_HORIZONTAL_583 0x247
#define CONS_FILP_VERTICAL_584 0x248
#define CONS_MIRROR_HORIZONTAL_585 0x249
#define CONS_MIRROR_VERTICAL_586 0x24A
#define CONS_FONT_SELECT_587 0x24B
#define CONS_FONT_COLOR_588 0x24C
#define CONS_FONT_SIZE_589 0x24D
#define CONS_JUSTIFY_LEFT_590 0x24E
#define CONS_JUSTIFY_CENTER_H_591 0x24F
#define CONS_JUSTIFY_RIGHT_592 0x250
#define CONS_JUSTIFY_BLOCK_H_593 0x251
#define CONS_JUSTIFY_TOP_594 0x252
#define CONS_JUSTIFY_CENTER_V_595 0x253
#define CONS_JUSTIFY_BOTTOM_596 0x254
#define CONS_JUSTIFY_BLOCK_V_597 0x255
#define CONS_INDENT_DECREASE_598 0x256
#define CONS_INDENT_INCREASE_599 0x257
#define CONS_NUMBERED_LIST_600 0x258
#define CONS_RESTART_NUMBERING_601 0x259
#define CONS_BULLETED_LIST_602 0x25A
#define CONS_PROMOTE_603 0x25B
#define CONS_DEMOTE_604 0x25C
#define CONS_YES_605 0x25D
#define CONS_NO_606 0x25E
#define CONS_CANCEL_607 0x25F
#define CONS_CATALOG_608 0x260
#define CONS_BUY_CHECKOUT_609 0x261
#define CONS_ADD_TO_CART_610 0x262
#define CONS_EXPAND_611 0x263
#define CONS_EXPAND_ALL_612 0x264
#define CONS_COLLAPSE_613 0x265
#define CONS_COLLAPSE_ALL_614 0x266
#define CONS_PRINT_PREVIEW_615 0x267
#define CONS_PASTE_SPECIAL_616 0x268
#define CONS_INSERT_MODE_617 0x269
#define CONS_DELETE_618 0x26A
#define CONS_LOCK_619 0x26B
#define CONS_UNLOCK_620 0x26C
#define CONS_PROTECT_621 0x26D
#define CONS_UNPROTECT_622 0x26E
#define CONS_ATTACH_COMMENT_623 0x26F
#define CONS_DELETE_COMMENT_624 0x270
#define CONS_VIEW_COMMENT_625 0x271
#define CONS_SELECT_WORD_626 0x272
#define CONS_SELECT_SENTENCE_627 0x273
#define CONS_SELECT_PARAGRAPH_628 0x274
#define CONS_SELECT_COLUMN_629 0x275
#define CONS_SELECT_ROW_630 0x276
#define CONS_SELECT_TABLE_631 0x277
#define CONS_SELECT_OBJECT_632 0x278
#define CONS_REDO_REPEAT_633 0x279
#define CONS_SORT_634 0x27A
#define CONS_SORT_ASCENDING_635 0x27B
#define CONS_SORT_DESCENDING_636 0x27C
#define CONS_FILTER_637 0x27D
#define CONS_SET_CLOCK_638 0x27E
#define CONS_VIEW_CLOCK_639 0x27F
#define CONS_SELECT_TIME_ZONE_640 0x280
#define CONS_EDIT_TIME_ZONE_641 0x281
#define CONS_SET_ALARM_642 0x282
#define CONS_CLEAR_ALARM_643 0x283
#define CONS_SNOOZE_ALARM_644 0x284
#define CONS_RESET_ALARM_645 0x285
#define CONS_SYNCHRONIZE_646 0x286
#define CONS_SEND_RECEIVE_647 0x287
#define CONS_SEND_TO_648 0x288
#define CONS_REPLY_649 0x289
#define CONS_REPLY_ALL_650 0x28A
#define CONS_FORWARD_MSG_651 0x28B
#define CONS_SEND_652 0x28C
#define CONS_ATTACH_FILE_653 0x28D
#define CONS_UPLOAD_654 0x28E
#define CONS_DOWNLOAD_655 0x28F
#define CONS_SET_BORDERS_656 0x290
#define CONS_INSERT_ROW_657 0x291
#define CONS_INSERT_COLUMN_658 0x292
#define CONS_INSERT_FILE_659 0x293
#define CONS_INSERT_PICTURE_660 0x294
#define CONS_INSERT_OBJECT_661 0x295
#define CONS_INSERT_SYMBOL_662 0x296
#define CONS_SAVE_AND_CLOSE_663 0x297
#define CONS_RENAME_664 0x298
#define CONS_MERGE_665 0x299
#define CONS_SPLIT_666 0x29A
#define CONS_DISTRIBUTE_HORIZONTALLY_667 0x29B
#define CONS_DISTRIBUTE_VERTICALLY_668 0x29C
#define CONS_NEXT_KEYBOARD_LAYOUT_SEL_669 0x29D


