/* Copyright (C) 2014-2018 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2018-11-17
// KLL Emitter:        kiibohd
// KLL Version:        0.5.6.6
// KLL Git Changes:    None
// Compiler arguments:
//    /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/__main__.py
//    --kiibohd-debug
//    --config
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Devices/MatrixARMPeriodic/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Macro/PartialMap/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Output/HID-IO/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Output/USB/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Debug/latency/capabilities.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Debug/led/capabilities.kll
//    --base
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Infinity_60/scancode_map.kll
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Scan/Infinity_60/scancode_map.alphabet.kll
//    --default
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/stdFuncMap.kll
//    --partial
//      /Users/tom/.local/share/virtualenvs/Keyboards-vdxSI5dA/lib/python3.7/site-packages/kll/layouts/ic60/hhkbpro2.kll
//    --emitter
//      kiibohd
//    --def-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.IC60.gcc.make/kll_defs.h
//    --map-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.IC60.gcc.make/generatedKeymap.h
//    --hid-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.IC60.gcc.make/usb_hid.h
//    --pixel-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.IC60.gcc.make/generatedPixelmap.c
//    --json-output
//      /Users/tom/dev/keyboard_utilities/ergodox/controller/Keyboards/darwin18.0.0.IC60.gcc.make/kll.json
//
// - Configuration File -
//    MatrixARMPeriodicCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll
//    PartialMapCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Macro_PartialMap@['capabilities']_processed.kll
//    HID-IOCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Output_HID-IO@['capabilities']_processed.kll
//    USBCapabilities
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Output_USB@['capabilities']_processed.kll
//    latency
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Debug_latency@['capabilities']_processed.kll
//    led
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Debug_led@['capabilities']_processed.kll
// - Generic Files -
// - Base Layer -
//    Infinity 60%
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Infinity_60@['scancode_map']_processed.kll
//    Infinity 60% Alphabet
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/dev_keyboard_utilities_ergodox_controller_Scan_Infinity_60@['scancode_map', 'alphabet']_processed.kll
// - Default Layer -
//    stdFuncMap
//      /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/.local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts@['stdFuncMap']_processed.kll
// - Partial Layers -
//    Layer 1
//     hhkbpro2
//       /var/folders/ft/swq49vbn0ll23744cl1yrl2w0000gn/T/kll/.local_share_virtualenvs_Keyboards-vdxSI5dA_lib_python3.7_site-packages_kll_layouts_ic60@['hhkbpro2']_processed.kll



#pragma once

// ----- Enums -----

// Capability Indices
typedef enum CapabilityIndex {
	Layer_layerLatch_capability_index,
	Layer_layerLock_capability_index,
	Layer_layerRotate_capability_index,
	Layer_layerShift_capability_index,
	Layer_layerState_capability_index,
	Macro_none_capability_index,
	Macro_rotate_capability_index,
	Macro_testThreadSafe_capability_index,
	Macro_testThreadUnsafe_capability_index,
	Output_consCtrlSend_capability_index,
	Output_flashMode_capability_index,
	Output_kbdProtocolBoot_capability_index,
	Output_kbdProtocolNKRO_capability_index,
	Output_noneSend_capability_index,
	Output_sysCtrlSend_capability_index,
	Output_toggleKbdProtocol_capability_index,
	Output_usbCodeSend_capability_index,
	Output_usbMouseWheel_capability_index,
	Output_usbMouse_capability_index,
} CapabilityIndex;



// ----- Defines -----

// -- Interconnect Node Maximum --
#define InterconnectNodeMax 0x2


// -- Capability / KLL Defines --

#define ActivityTimerMultiplier_define 1
#define ResultCapabilityStackSize_define 10
#define MinDebounceTime_define 6
#define Output_HIDIOEnabled_define 1
#define Output_USBEnabled_define 1
#define PeriodicCycles_define 1000
#define PressReleaseCache_define 1
#define ResultMacroBufferSize_define 50
#define ScanCodeMatrixType_define GPIO_Config_Pulldown
#define ScanCodeRemapping_define 0
#define ScanCodeRemappingMatrix_define 
#define ScanCodeSenseList_define  \
	gpio(D,1), \
	gpio(D,2), \
	gpio(D,3), \
	gpio(D,4), \
	gpio(D,5), \
	gpio(D,6), \
	gpio(D,7) \

#define ScanCodeStrobeList_define  \
	gpio(B,0), \
	gpio(B,1), \
	gpio(B,2), \
	gpio(B,3), \
	gpio(B,16), \
	gpio(B,17), \
	gpio(C,4), \
	gpio(C,5), \
	gpio(D,0) \

#define StrobeDelay_define 0
#define enableDeviceRestartOnUSBTimeout_define 0
#define enableJoystick_define 0
#define enableKeyboard_define 1
#define enableMouse_define 1
#define enableRawIO_define 1
#define enableUSBLowPowerNegotiation_define 0
#define enableUSBResume_define 1
#define enableUSBSuspend_define 1
#define enableVirtualSerialPort_define 1
#define flashModeEnabled_define 0
#define IndexWordSize_define 16
#define KeyboardLocale_define 0
#define LatencyMeasurementCount_define 10
#define DebugLED_ErrorPin_define gpio(A,19)
#define SecureBootloader_define 0
#define StateWordSize_define 16
#define USBIdle_define 0
#define USBIdle_force_define 1
#define USBProtocol_define 1

// -- Animation Defines --


// -- Built-in Defines --
#define CapabilitiesNum_KLL 19
#define LayerNum_KLL 2
#define ResultMacroNum_KLL 94
#define TriggerMacroNum_KLL 95
#define MaxScanCode_KLL 63
#define RotationNum_KLL 0
#define AnimationNum_KLL 0


